interface JsonObject {
  [key: string]: unknown;
}

const PROJECT_ROOT = new URL("../", import.meta.url);
const OUTPUT_PATHS = [
  new URL("server/functions/_shared/pve_arena_catalog.ts", PROJECT_ROOT),
  new URL("supabase/functions/_shared/pve_arena_catalog.ts", PROJECT_ROOT),
];

const arenasPayload = await readDefinition("pve_arenas.json");
const difficultiesPayload = await readDefinition("pve_arena_difficulties.json");
const enemiesPayload = await readDefinition("pve_enemies.json");
const buffsPayload = await readDefinition("arena_buffs.json");
const rewardsPayload = await readDefinition("arena_rewards.json");

const catalog = {
  schema_version: "pve_arena_catalog_v1",
  source_collections: [
    "pve_arenas",
    "pve_arena_difficulties",
    "pve_enemies",
    "arena_buffs",
    "arena_rewards",
  ],
  season_id: "season_001",
  mode: "PVE_ARENA_V1",
  target_power_model: "arena_tuning_power_v1",
  generated_at: "BUILD_TIME_REPLACED_BY_SOURCE_HASH",
  arenas: objectItems(arenasPayload),
  difficulty_ladder: arrayObjects(difficultiesPayload, "difficulty_ladder"),
  difficulty_tiers: objectItems(difficultiesPayload),
  enemy_sequences: arrayObjects(difficultiesPayload, "enemy_sequences"),
  duel_power_distributions: objectField(difficultiesPayload, "duel_power_distributions"),
  enemies: objectItems(enemiesPayload),
  buffs: objectItems(buffsPayload),
  rewards: objectItems(rewardsPayload),
};

const body =
  `// Generated by tools/generate_pve_arena_catalog.ts. Do not edit by hand.
export const PVE_ARENA_CATALOG = ${JSON.stringify(catalog, null, 2)} as const;

export type PveArenaCatalog = typeof PVE_ARENA_CATALOG;
export type PveArenaDefinition = PveArenaCatalog["arenas"][number];
export type PveArenaDifficultyTier = PveArenaCatalog["difficulty_tiers"][number];
export type PveArenaEnemyDefinition = PveArenaCatalog["enemies"][number];
export type PveArenaRewardProfile = PveArenaCatalog["rewards"][number];
export type PveArenaBuffDefinition = PveArenaCatalog["buffs"][number];

export interface ArenaProgressSnapshot {
  tutorial_completed?: boolean;
  best_completed_difficulty?: number;
  best_completed_length?: number;
  metadata?: {
    completed_tiers?: Record<string, unknown>;
    completed_arenas?: Record<string, unknown>;
    [key: string]: unknown;
  };
  [key: string]: unknown;
}

export interface ArenaPlayerSnapshot {
  level?: number;
  power?: number;
  [key: string]: unknown;
}

export interface ArenaUnlockState {
  arena_id: string;
  difficulty_id: string;
  unlocked: boolean;
  reason: string;
}

export function arenaDefinitions(): PveArenaDefinition[] {
  return cloneArray(PVE_ARENA_CATALOG.arenas);
}

export function arenaDifficultyTiers(): PveArenaDifficultyTier[] {
  return cloneArray(PVE_ARENA_CATALOG.difficulty_tiers);
}

export function arenaTierById(
  arenaId: string,
  difficultyId: string,
): PveArenaDifficultyTier | null {
  const tier = PVE_ARENA_CATALOG.difficulty_tiers.find((item) =>
    item.arena_id === arenaId && item.difficulty_id === difficultyId
  );
  return tier === undefined ? null : clone(tier);
}

export function arenaRewardProfile(
  rewardProfileId: string,
): PveArenaRewardProfile | null {
  const reward = PVE_ARENA_CATALOG.rewards.find((item) => item.id === rewardProfileId);
  return reward === undefined ? null : clone(reward);
}

export function pveEnemyDefinition(enemyId: string): PveArenaEnemyDefinition | null {
  const enemy = PVE_ARENA_CATALOG.enemies.find((item) => item.id === enemyId);
  return enemy === undefined ? null : clone(enemy);
}

export function arenaBuffDefinitions(): PveArenaBuffDefinition[] {
  return cloneArray(PVE_ARENA_CATALOG.buffs);
}

export function arenaTierUnlockState(
  progress: ArenaProgressSnapshot | null | undefined,
  player: ArenaPlayerSnapshot | null | undefined,
  arenaId?: string,
  difficultyId?: string,
): ArenaUnlockState[] {
  const tiers = PVE_ARENA_CATALOG.difficulty_tiers.filter((tier) =>
    (arenaId === undefined || tier.arena_id === arenaId) &&
    (difficultyId === undefined || tier.difficulty_id === difficultyId)
  );
  return tiers.map((tier) => unlockStateForTier(tier, progress ?? {}, player ?? {}));
}

function unlockStateForTier(
  tier: PveArenaDifficultyTier,
  progress: ArenaProgressSnapshot,
  player: ArenaPlayerSnapshot,
): ArenaUnlockState {
  const arena = PVE_ARENA_CATALOG.arenas.find((item) => item.id === tier.arena_id);
  if (arena === undefined) {
    return {
      arena_id: tier.arena_id,
      difficulty_id: tier.difficulty_id,
      unlocked: false,
      reason: "Arena desconhecida",
    };
  }

  const arenaGate = arenaUnlockReason(arena, progress);
  if (arenaGate !== "") {
    return {
      arena_id: tier.arena_id,
      difficulty_id: tier.difficulty_id,
      unlocked: false,
      reason: arenaGate,
    };
  }

  const playerLevel = safeNumber(player.level, 1);
  if (playerLevel + 1 < tier.recommended_level_min) {
    return {
      arena_id: tier.arena_id,
      difficulty_id: tier.difficulty_id,
      unlocked: false,
      reason: \`Recomendada para level \${tier.recommended_level_min}\`,
    };
  }

  const bestRank = safeNumber(progress.best_completed_difficulty, -1);
  if (tier.difficulty_rank > bestRank + 1) {
    return {
      arena_id: tier.arena_id,
      difficulty_id: tier.difficulty_id,
      unlocked: false,
      reason: "Conclua a dificuldade anterior",
    };
  }

  return {
    arena_id: tier.arena_id,
    difficulty_id: tier.difficulty_id,
    unlocked: true,
    reason: "Disponivel",
  };
}

function arenaUnlockReason(
  arena: PveArenaDefinition,
  progress: ArenaProgressSnapshot,
): string {
  const unlock = arena.unlock as { type?: string; arena_id?: string };
  if (unlock.type === "always") {
    return "";
  }
  if (unlock.type !== "arena_first_clear" || unlock.arena_id === undefined) {
    return "Bloqueio de arena desconhecido";
  }
  if (hasCompletedArena(progress, unlock.arena_id)) {
    return "";
  }
  const requiredArena = PVE_ARENA_CATALOG.arenas.find((item) => item.id === unlock.arena_id);
  return requiredArena === undefined
    ? "Conclua a arena anterior"
    : \`Conclua \${requiredArena.display_name}\`;
}

function hasCompletedArena(progress: ArenaProgressSnapshot, arenaId: string): boolean {
  if (arenaId === "arena_tutorial_cinzas" && progress.tutorial_completed === true) {
    return true;
  }
  const completedArenas = progress.metadata?.completed_arenas;
  if (completedArenas !== undefined && completedArenas[arenaId] === true) {
    return true;
  }
  const completedTiers = progress.metadata?.completed_tiers;
  if (completedTiers !== undefined) {
    for (const key of Object.keys(completedTiers)) {
      if (key.startsWith(\`\${arenaId}:\`) && completedTiers[key] === true) {
        return true;
      }
    }
  }
  const arena = PVE_ARENA_CATALOG.arenas.find((item) => item.id === arenaId);
  return arena !== undefined && safeNumber(progress.best_completed_length, 0) >= arena.duel_count;
}

function safeNumber(value: unknown, fallback: number): number {
  return typeof value === "number" && Number.isFinite(value) ? value : fallback;
}

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

function cloneArray<T>(value: readonly T[]): T[] {
  return value.map((item) => clone(item));
}
`;

for (const outputPath of OUTPUT_PATHS) {
  await Deno.mkdir(new URL(".", outputPath), { recursive: true });
  await Deno.writeTextFile(outputPath, body);
}

console.log("[generate-pve-arena-catalog] OK", {
  arenas: catalog.arenas.length,
  tiers: catalog.difficulty_tiers.length,
  enemies: catalog.enemies.length,
  buffs: catalog.buffs.length,
  rewards: catalog.rewards.length,
});

async function readDefinition(fileName: string): Promise<JsonObject> {
  const url = new URL(`data/definitions/${fileName}`, PROJECT_ROOT);
  return assertObject(JSON.parse(await Deno.readTextFile(url)));
}

function objectItems(payload: JsonObject): JsonObject[] {
  return arrayObjects(payload, "items");
}

function arrayObjects(payload: JsonObject, key: string): JsonObject[] {
  const value = payload[key];
  if (!Array.isArray(value)) {
    throw new Error(`Expected ${key} to be an array.`);
  }
  return value.map((item) => assertObject(item));
}

function objectField(payload: JsonObject, key: string): JsonObject {
  return assertObject(payload[key], `Expected ${key} to be an object.`);
}

function assertObject(
  value: unknown,
  message = "Expected value to be an object.",
): JsonObject {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    throw new Error(message);
  }
  return value as JsonObject;
}
