interface DefinitionDocument {
  schema_version?: number;
  collection?: string;
  items?: unknown[];
}

interface CollectionSpec {
  sourceFile: string;
  outputKey: string;
}

const PROJECT_ROOT = new URL("../", import.meta.url);
const DEFINITIONS_ROOT = new URL("data/definitions/", PROJECT_ROOT);
const OUTPUT_PATHS = [
  new URL("supabase/functions/_shared/grimoire_catalog.ts", PROJECT_ROOT),
  new URL("server/functions/_shared/grimoire_catalog.ts", PROJECT_ROOT),
];
const PORTAL_JSON_PATH = new URL(
  "portal/internal-alpha/assets/grimoire-catalog.json",
  PROJECT_ROOT,
);

const COLLECTIONS: CollectionSpec[] = [
  { sourceFile: "weapons.json", outputKey: "weapons" },
  { sourceFile: "spells.json", outputKey: "spells" },
  { sourceFile: "passives.json", outputKey: "doutrines" },
  { sourceFile: "pets.json", outputKey: "familiars" },
  { sourceFile: "base_structures.json", outputKey: "base_structures" },
  { sourceFile: "rewards.json", outputKey: "rewards" },
  { sourceFile: "power_bands.json", outputKey: "power_bands" },
  { sourceFile: "bot_builds.json", outputKey: "bot_archetypes" },
];

const collections: Record<string, unknown[]> = {};
const source_files: Record<string, string> = {};

for (const spec of COLLECTIONS) {
  const sourceUrl = new URL(spec.sourceFile, DEFINITIONS_ROOT);
  const document = JSON.parse(
    await Deno.readTextFile(sourceUrl),
  ) as DefinitionDocument;
  const items = Array.isArray(document.items) ? document.items : [];
  collections[spec.outputKey] = sortItems(items);
  source_files[spec.outputKey] = `data/definitions/${spec.sourceFile}`;
}

const counts = Object.fromEntries(
  Object.entries(collections).map(([key, items]) => [key, items.length]),
);

const catalog = {
  schema_version: "grimoire_catalog_v1",
  catalog_version: "internal_alpha_v0",
  source: "data/definitions",
  source_files,
  collections,
  counts,
};

const body =
  `// Generated by tools/generate_grimoire_catalog.ts. Do not edit by hand.
export const GRIMOIRE_CATALOG = ${JSON.stringify(catalog, null, 2)} as const;

export type GrimoireCatalog = typeof GRIMOIRE_CATALOG;

export function grimoireCatalog(): GrimoireCatalog {
  return JSON.parse(JSON.stringify(GRIMOIRE_CATALOG)) as GrimoireCatalog;
}
`;

for (const outputUrl of OUTPUT_PATHS) {
  await Deno.mkdir(new URL(".", outputUrl), { recursive: true });
  await Deno.writeTextFile(outputUrl, body);
}
await Deno.mkdir(new URL(".", PORTAL_JSON_PATH), { recursive: true });
await Deno.writeTextFile(
  PORTAL_JSON_PATH,
  `${JSON.stringify({ ok: true, ...catalog }, null, 2)}\n`,
);

console.log("[generate-grimoire-catalog] OK", counts);

function sortItems(items: unknown[]): unknown[] {
  return [...items].sort((left, right) =>
    itemSortKey(left).localeCompare(itemSortKey(right), "en")
  );
}

function itemSortKey(value: unknown): string {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    return "";
  }
  const record = value as Record<string, unknown>;
  const name = typeof record.display_name === "string"
    ? record.display_name
    : "";
  const id = typeof record.id === "string" ? record.id : "";
  return `${name.toLowerCase()}|${id.toLowerCase()}`;
}
