type SourceKind = "definition_json" | "tool_model" | "battle_simulator";
type CanonicalizationMode = "json" | "text";

interface SourceSpec {
  path: string;
  kind: SourceKind;
  canonicalization: CanonicalizationMode;
}

interface SourceDigest {
  path: string;
  kind: SourceKind;
  sha256: string;
  canonical_bytes: number;
}

const PROJECT_ROOT = new URL("../", import.meta.url);
const RULESET_ID = "foundation_ruleset_v0";
const RULESET_PATH = new URL(
  "data/rulesets/foundation_ruleset_v0.json",
  PROJECT_ROOT,
);
const OUTPUT_PATHS = [
  new URL("server/functions/_shared/foundation_ruleset.ts", PROJECT_ROOT),
  new URL("supabase/functions/_shared/foundation_ruleset.ts", PROJECT_ROOT),
];

const CONTENT_SOURCES: SourceSpec[] = [
  "arena_buffs.json",
  "arena_rewards.json",
  "base_structures.json",
  "battle_fixtures.json",
  "bot_builds.json",
  "crafting_recipes.json",
  "passives.json",
  "pets.json",
  "potions.json",
  "power_bands.json",
  "pve_arena_difficulties.json",
  "pve_arenas.json",
  "pve_enemies.json",
  "rewards.json",
  "spells.json",
  "weapons.json",
].map((fileName) => ({
  path: `data/definitions/${fileName}`,
  kind: "definition_json",
  canonicalization: "json",
}));

const TOOL_MODEL_SOURCES: SourceSpec[] = [
  "tools/battle_lab/model.v1.json",
  "tools/economy_simulator/economy_model.v1.json",
  "tools/progression_lab/model.v1.json",
].map((path) => ({
  path,
  kind: "tool_model",
  canonicalization: "json",
}));

const SIMULATOR_SOURCES: SourceSpec[] = [
  "server/functions/_shared/battle_combatants.ts",
  "server/functions/_shared/battle_simulator.ts",
  "supabase/functions/_shared/battle_combatants.ts",
  "supabase/functions/_shared/battle_simulator.ts",
].map((path) => ({
  path,
  kind: "battle_simulator",
  canonicalization: "text",
}));

const contentSources = await digestSources([
  ...CONTENT_SOURCES,
  ...TOOL_MODEL_SOURCES,
]);
const simulatorSources = await digestSources(SIMULATOR_SOURCES);

assertMirroredSimulatorSources(simulatorSources);

const contentHash = await sha256Hex(`${stableStringify(contentSources)}\n`);
const simulatorHash = await sha256Hex(`${stableStringify(simulatorSources)}\n`);
const sources = [...contentSources, ...simulatorSources];

const ruleset = {
  schema_version: "foundation_ruleset_manifest_v1",
  ruleset_id: RULESET_ID,
  ruleset_version: 1,
  lifecycle: "FOUNDATION_AUDIT_ACTIVE",
  primary_product_mode: "PVE_ARENA_INITIAL",
  content_hash: contentHash,
  simulator_hash: simulatorHash,
  runtime: {
    mode: "FIRST_SLICE_SIM",
    primary_product_mode: "PVE_ARENA_INITIAL",
    battle_log_schema: "battle_log_v1",
    catalog_schema: "grimoire_catalog_v1",
    server_authoritative: true,
  },
  sources,
  counts: {
    definitions:
      contentSources.filter((source) => source.kind === "definition_json")
        .length,
    tool_models:
      contentSources.filter((source) => source.kind === "tool_model").length,
    battle_simulators: simulatorSources.length,
    total_sources: sources.length,
  },
};

const jsonBody = `${JSON.stringify(ruleset, null, 2)}\n`;
const moduleBody =
  `// Generated by tools/generate_foundation_ruleset.ts. Do not edit by hand.
export const FOUNDATION_RULESET = ${JSON.stringify(ruleset, null, 2)} as const;

export type FoundationRuleset = typeof FOUNDATION_RULESET;

export function foundationRuleset(): FoundationRuleset {
  return JSON.parse(JSON.stringify(FOUNDATION_RULESET)) as FoundationRuleset;
}
`;

await Deno.mkdir(new URL(".", RULESET_PATH), { recursive: true });
await Deno.writeTextFile(RULESET_PATH, jsonBody);

for (const outputPath of OUTPUT_PATHS) {
  await Deno.mkdir(new URL(".", outputPath), { recursive: true });
  await Deno.writeTextFile(outputPath, moduleBody);
}

console.log("[generate-foundation-ruleset] OK", {
  ruleset_id: RULESET_ID,
  content_hash: contentHash,
  simulator_hash: simulatorHash,
  sources: sources.length,
});

async function digestSources(specs: SourceSpec[]): Promise<SourceDigest[]> {
  const digests: SourceDigest[] = [];
  for (const spec of specs) {
    const canonicalBody = await canonicalSourceBody(spec);
    digests.push({
      path: spec.path,
      kind: spec.kind,
      sha256: await sha256Hex(canonicalBody),
      canonical_bytes: new TextEncoder().encode(canonicalBody).byteLength,
    });
  }
  return digests.sort((left, right) =>
    left.path.localeCompare(right.path, "en")
  );
}

async function canonicalSourceBody(spec: SourceSpec): Promise<string> {
  const sourcePath = new URL(spec.path, PROJECT_ROOT);
  const text = await Deno.readTextFile(sourcePath);
  if (spec.canonicalization === "json") {
    return `${stableStringify(JSON.parse(text))}\n`;
  }
  return `${text.replaceAll("\r\n", "\n").trimEnd()}\n`;
}

async function sha256Hex(text: string): Promise<string> {
  const bytes = new TextEncoder().encode(text);
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return [...new Uint8Array(digest)]
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("");
}

function stableStringify(value: unknown): string {
  if (value === null || typeof value !== "object") {
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) {
    return `[${value.map((item) => stableStringify(item)).join(",")}]`;
  }
  return `{${
    Object.entries(value as Record<string, unknown>)
      .sort(([left], [right]) => left.localeCompare(right, "en"))
      .map(([key, item]) => `${JSON.stringify(key)}:${stableStringify(item)}`)
      .join(",")
  }}`;
}

function assertMirroredSimulatorSources(sources: SourceDigest[]): void {
  const byPath = new Map(sources.map((source) => [source.path, source]));
  for (const source of sources) {
    if (!source.path.startsWith("server/functions/")) {
      continue;
    }
    const mirrorPath = source.path.replace(
      "server/functions/",
      "supabase/functions/",
    );
    const mirror = byPath.get(mirrorPath);
    if (mirror === undefined || mirror.sha256 !== source.sha256) {
      throw new Error(
        `Battle simulator mirror mismatch: ${source.path} -> ${mirrorPath}.`,
      );
    }
  }
}
