// Generated by tools/generate_foundation_ruleset.ts. Do not edit by hand.
export const FOUNDATION_RULESET = {
  "schema_version": "foundation_ruleset_manifest_v1",
  "ruleset_id": "foundation_ruleset_v0",
  "ruleset_version": 1,
  "lifecycle": "FOUNDATION_AUDIT_ACTIVE",
  "primary_product_mode": "PVE_ARENA_INITIAL",
  "content_hash": "c9cb2166c562272170c24063fe271bd03f165c39c772b71d3700575ca8bbcc86",
  "simulator_hash": "657d89817244c90605d00aec31a5bc7fe681ca1879c38925af1e3cddb7254381",
  "runtime": {
    "mode": "FIRST_SLICE_SIM",
    "primary_product_mode": "PVE_ARENA_INITIAL",
    "battle_log_schema": "battle_log_v1",
    "catalog_schema": "grimoire_catalog_v1",
    "server_authoritative": true
  },
  "sources": [
    {
      "path": "data/definitions/arena_buffs.json",
      "kind": "definition_json",
      "sha256": "8f7fc6946749df4894c6d7d9c9e4db85d4af667bcbccf576904fe743b7a2ed59",
      "canonical_bytes": 3379
    },
    {
      "path": "data/definitions/arena_rewards.json",
      "kind": "definition_json",
      "sha256": "30d61b1e6368370cabc3896698c6d1017eba2f9380634f9192b203b026659631",
      "canonical_bytes": 21847
    },
    {
      "path": "data/definitions/base_structures.json",
      "kind": "definition_json",
      "sha256": "45eb863e380dd94595a16fa8d405bf089361f569c22f70a06ef1e4f933c6407b",
      "canonical_bytes": 2800
    },
    {
      "path": "data/definitions/battle_fixtures.json",
      "kind": "definition_json",
      "sha256": "7120ddc085cd23b4739a10c95d097a7bac0dacbd51e58cd9acb05dbe14d8cd79",
      "canonical_bytes": 1042
    },
    {
      "path": "data/definitions/bot_builds.json",
      "kind": "definition_json",
      "sha256": "f2b0960f726e03d60c19f2eef23daec9687432d6090fb951caf8e73bb494702f",
      "canonical_bytes": 4852
    },
    {
      "path": "data/definitions/crafting_recipes.json",
      "kind": "definition_json",
      "sha256": "199df9f689704f9da280779c9e37136de72f0e4fb84657ee20fbfb7b6975c940",
      "canonical_bytes": 1974
    },
    {
      "path": "data/definitions/passives.json",
      "kind": "definition_json",
      "sha256": "4472336d3e3443b29088a7f27dd6fc6b981366354c494cf5acc90973cae2040b",
      "canonical_bytes": 4252
    },
    {
      "path": "data/definitions/pets.json",
      "kind": "definition_json",
      "sha256": "900ea0d76b237ddf52eaf3877908bda5a93932648b65bd0bf26755ad505e8359",
      "canonical_bytes": 4064
    },
    {
      "path": "data/definitions/potions.json",
      "kind": "definition_json",
      "sha256": "5d073076615a3ddd8faaaa95bc6f559835426d2b158993b0fb8ecb6fe2046711",
      "canonical_bytes": 1314
    },
    {
      "path": "data/definitions/power_bands.json",
      "kind": "definition_json",
      "sha256": "e65aa003f9a875ae5ff604b57510ebf5f1d0bf6fea9b7e2357cb33a281c4df2b",
      "canonical_bytes": 1619
    },
    {
      "path": "data/definitions/pve_arena_difficulties.json",
      "kind": "definition_json",
      "sha256": "65a95492ba44cc1196d4a197adde9aa050db74f1c6a47a72dcfa03f24643603b",
      "canonical_bytes": 26895
    },
    {
      "path": "data/definitions/pve_arenas.json",
      "kind": "definition_json",
      "sha256": "6bccbb35e7f7d4c9377eaf6e0b768125fd74fbe26bf468f94f53e4484005610d",
      "canonical_bytes": 5692
    },
    {
      "path": "data/definitions/pve_enemies.json",
      "kind": "definition_json",
      "sha256": "f26f60fc435556cd562842b85bfda91636f8f08b5b282558d2e417198b5e91e6",
      "canonical_bytes": 6197
    },
    {
      "path": "data/definitions/rewards.json",
      "kind": "definition_json",
      "sha256": "310acb38bea00a24cf886c30f44d26ab5cd13c078a024a7c59756f91794380a0",
      "canonical_bytes": 2144
    },
    {
      "path": "data/definitions/season_1_progression_targets.json",
      "kind": "definition_json",
      "sha256": "ae2445c315ef9fd1844e5eb6c0eed9d97a71e59e1b8fcea24f617224a4df7c67",
      "canonical_bytes": 2379
    },
    {
      "path": "data/definitions/spells.json",
      "kind": "definition_json",
      "sha256": "a8b80adaa7dca32f41591311af4d595b656924c92ee27c516231a1844184b4d0",
      "canonical_bytes": 9656
    },
    {
      "path": "data/definitions/weapons.json",
      "kind": "definition_json",
      "sha256": "e0a0da2b16be7ae71fcbef78dd99fc95e758dec880d6e4c73e41895e7d804075",
      "canonical_bytes": 4141
    },
    {
      "path": "tools/battle_lab/model.v1.json",
      "kind": "tool_model",
      "sha256": "c51ae399980e6b1499d2cdaec4f245b4663e13b6f504e89b8cca5865876b57ac",
      "canonical_bytes": 6387
    },
    {
      "path": "tools/economy_simulator/economy_model.v1.json",
      "kind": "tool_model",
      "sha256": "2648a04a6c3cd3f5f62b7e503d0c9df72b00a7289c54b60ada77ce8b09c21342",
      "canonical_bytes": 7440
    },
    {
      "path": "tools/progression_lab/model.v1.json",
      "kind": "tool_model",
      "sha256": "9a2ebc9a5dfd1636f6c6ee13863bc87c8188a263135b718b40b15eadc001664a",
      "canonical_bytes": 5384
    },
    {
      "path": "server/functions/_shared/battle_combatants.ts",
      "kind": "battle_simulator",
      "sha256": "ff1fc69b18dcf218d1fb46d0fd6ec611f13bca1d59949722dff8074f19c32747",
      "canonical_bytes": 8118
    },
    {
      "path": "server/functions/_shared/battle_simulator.ts",
      "kind": "battle_simulator",
      "sha256": "e49c9dee853c136c3ac4f72398c65ac748235af48b259b6433e119e23d5815dd",
      "canonical_bytes": 55109
    },
    {
      "path": "supabase/functions/_shared/battle_combatants.ts",
      "kind": "battle_simulator",
      "sha256": "ff1fc69b18dcf218d1fb46d0fd6ec611f13bca1d59949722dff8074f19c32747",
      "canonical_bytes": 8118
    },
    {
      "path": "supabase/functions/_shared/battle_simulator.ts",
      "kind": "battle_simulator",
      "sha256": "e49c9dee853c136c3ac4f72398c65ac748235af48b259b6433e119e23d5815dd",
      "canonical_bytes": 55109
    }
  ],
  "counts": {
    "definitions": 17,
    "tool_models": 3,
    "battle_simulators": 4,
    "total_sources": 24
  }
} as const;

export type FoundationRuleset = typeof FOUNDATION_RULESET;

export function foundationRuleset(): FoundationRuleset {
  return JSON.parse(JSON.stringify(FOUNDATION_RULESET)) as FoundationRuleset;
}
