// Generated by tools/generate_pve_arena_catalog.ts. Do not edit by hand.
export const PVE_ARENA_CATALOG = {
  "schema_version": "pve_arena_catalog_v1",
  "source_collections": [
    "pve_arenas",
    "pve_arena_difficulties",
    "pve_enemies",
    "arena_buffs",
    "arena_rewards"
  ],
  "season_id": "season_001",
  "mode": "PVE_ARENA_V1",
  "target_power_model": "arena_tuning_power_v1",
  "generated_at": "BUILD_TIME_REPLACED_BY_SOURCE_HASH",
  "arenas": [
    {
      "id": "arena_tutorial_cinzas",
      "display_name": "Tutorial: Cinzas Do Refugio",
      "description": "Arena guiada de 1 duelo para ensinar pedido de batalha, replay, recompensa e retorno ao Refugio.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "tutorial",
        "initial_release"
      ],
      "mode": "PVE_ARENA_V1",
      "duel_count": 1,
      "difficulty_tier": 0,
      "difficulty_catalog": {
        "source_collection": "pve_arena_difficulties",
        "default_difficulty_id": "s1_d00_intro",
        "season_1_difficulty_ids": [
          "s1_d00_intro"
        ]
      },
      "initial_release": true,
      "unlock": {
        "type": "always"
      },
      "enemy_sequence": [
        "pve_aprendiz_cinzas"
      ],
      "buff_offer_count": 0,
      "buffs_after_duels": [],
      "reward_profile_id": "arena_tutorial_clear",
      "attempt_rules": {
        "lock_loadout": true,
        "reset_hp_each_duel": true,
        "combat_cooldown_seconds": 0,
        "allow_behavior_between_duels": true,
        "allow_loadout_swap_between_duels": false,
        "failure_ends_attempt": true
      },
      "records": {
        "track_best_duel_index": true,
        "track_first_clear": true,
        "track_completion_count": true
      }
    },
    {
      "id": "arena_cinzas_curta",
      "display_name": "Arena Curta Das Cinzas",
      "description": "Primeira arena real de 3 duelos, com buffs temporarios entre lutas e inimigos de leitura simples.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "short",
        "initial_release"
      ],
      "mode": "PVE_ARENA_V1",
      "duel_count": 3,
      "difficulty_tier": 1,
      "difficulty_catalog": {
        "source_collection": "pve_arena_difficulties",
        "default_difficulty_id": "s1_d00_intro",
        "season_1_difficulty_ids": [
          "s1_d00_intro",
          "s1_d01_aprendiz",
          "s1_d02_iniciado",
          "s1_d03_adepto",
          "s1_d04_familiar",
          "s1_d05_arcano",
          "s1_d06_evocador",
          "s1_d07_mestre",
          "s1_d08_abissal"
        ]
      },
      "initial_release": true,
      "unlock": {
        "type": "arena_first_clear",
        "arena_id": "arena_tutorial_cinzas"
      },
      "enemy_sequence": [
        "pve_aprendiz_cinzas",
        "pve_guardiao_barreira",
        "pve_sussurrador_veu"
      ],
      "buff_offer_count": 3,
      "buffs_after_duels": [
        1,
        2
      ],
      "reward_profile_id": "arena_3_duel_clear_d1",
      "attempt_rules": {
        "lock_loadout": true,
        "reset_hp_each_duel": true,
        "combat_cooldown_seconds": 0,
        "allow_behavior_between_duels": true,
        "allow_loadout_swap_between_duels": false,
        "failure_ends_attempt": true
      },
      "records": {
        "track_best_duel_index": true,
        "track_first_clear": true,
        "track_completion_count": true
      }
    },
    {
      "id": "arena_veu_curta",
      "display_name": "Arena Do Veu",
      "description": "Arena de 4 duelos para testar controle mental, pressao de DoT e mistura elemental inicial.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "medium",
        "initial_release",
        "difficulty_2"
      ],
      "mode": "PVE_ARENA_V1",
      "duel_count": 4,
      "difficulty_tier": 2,
      "difficulty_catalog": {
        "source_collection": "pve_arena_difficulties",
        "default_difficulty_id": "s1_d02_iniciado",
        "season_1_difficulty_ids": [
          "s1_d02_iniciado",
          "s1_d03_adepto",
          "s1_d04_familiar",
          "s1_d05_arcano",
          "s1_d06_evocador",
          "s1_d07_mestre",
          "s1_d08_abissal"
        ]
      },
      "initial_release": true,
      "unlock": {
        "type": "arena_first_clear",
        "arena_id": "arena_cinzas_curta"
      },
      "enemy_sequence": [
        "pve_sussurrador_veu",
        "pve_pressao_veneno",
        "pve_guardiao_barreira",
        "pve_misturador_elemental"
      ],
      "buff_offer_count": 3,
      "buffs_after_duels": [
        1,
        2,
        3
      ],
      "reward_profile_id": "arena_4_duel_clear_d2",
      "attempt_rules": {
        "lock_loadout": true,
        "reset_hp_each_duel": true,
        "combat_cooldown_seconds": 0,
        "allow_behavior_between_duels": true,
        "allow_loadout_swap_between_duels": false,
        "failure_ends_attempt": true
      },
      "records": {
        "track_best_duel_index": true,
        "track_first_clear": true,
        "track_completion_count": true
      }
    },
    {
      "id": "arena_ossos_media",
      "display_name": "Arena Da Tempestade",
      "description": "Primeira arena de 5 duelos, contratada para liberar comprimento maior depois das arenas curtas.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "long",
        "contracted",
        "difficulty_3"
      ],
      "mode": "PVE_ARENA_V1",
      "duel_count": 5,
      "difficulty_tier": 3,
      "difficulty_catalog": {
        "source_collection": "pve_arena_difficulties",
        "default_difficulty_id": "s1_d04_familiar",
        "season_1_difficulty_ids": [
          "s1_d04_familiar",
          "s1_d05_arcano",
          "s1_d06_evocador",
          "s1_d07_mestre",
          "s1_d08_abissal"
        ]
      },
      "initial_release": false,
      "unlock": {
        "type": "arena_first_clear",
        "arena_id": "arena_veu_curta"
      },
      "enemy_sequence": [
        "pve_guardiao_barreira",
        "pve_pressao_veneno",
        "pve_condutor_familiar",
        "pve_misturador_elemental",
        "pve_invocador_ossario"
      ],
      "buff_offer_count": 3,
      "buffs_after_duels": [
        1,
        2,
        3,
        4
      ],
      "reward_profile_id": "arena_5_duel_clear_d3",
      "attempt_rules": {
        "lock_loadout": true,
        "reset_hp_each_duel": true,
        "combat_cooldown_seconds": 0,
        "allow_behavior_between_duels": true,
        "allow_loadout_swap_between_duels": false,
        "failure_ends_attempt": true
      },
      "records": {
        "track_best_duel_index": true,
        "track_first_clear": true,
        "track_completion_count": true
      }
    },
    {
      "id": "arena_abismo_longa",
      "display_name": "Arena Longa Do Abismo",
      "description": "Cap inicial de 6 duelos para validar comprimento maximo v1 sem campanha PVE tradicional.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "long",
        "contracted",
        "difficulty_4",
        "initial_cap"
      ],
      "mode": "PVE_ARENA_V1",
      "duel_count": 6,
      "difficulty_tier": 4,
      "difficulty_catalog": {
        "source_collection": "pve_arena_difficulties",
        "default_difficulty_id": "s1_d05_arcano",
        "season_1_difficulty_ids": [
          "s1_d05_arcano",
          "s1_d06_evocador",
          "s1_d07_mestre",
          "s1_d08_abissal",
          "s1_d09_capstone"
        ]
      },
      "initial_release": false,
      "unlock": {
        "type": "arena_first_clear",
        "arena_id": "arena_ossos_media"
      },
      "enemy_sequence": [
        "pve_misturador_elemental",
        "pve_condutor_familiar",
        "pve_invocador_ossario",
        "pve_defensor_abissal",
        "pve_pressao_veneno",
        "pve_finalizador_abissal"
      ],
      "buff_offer_count": 3,
      "buffs_after_duels": [
        1,
        2,
        3,
        4,
        5
      ],
      "reward_profile_id": "arena_6_duel_clear_d4",
      "attempt_rules": {
        "lock_loadout": true,
        "reset_hp_each_duel": true,
        "combat_cooldown_seconds": 0,
        "allow_behavior_between_duels": true,
        "allow_loadout_swap_between_duels": false,
        "failure_ends_attempt": true
      },
      "records": {
        "track_best_duel_index": true,
        "track_first_clear": true,
        "track_completion_count": true
      }
    }
  ],
  "difficulty_ladder": [
    {
      "id": "s1_d00_intro",
      "display_name": "Intro",
      "rank": 0,
      "recommended_level_min": 1,
      "recommended_level_max": 4,
      "recommended_power_min": 80,
      "recommended_power_max": 260,
      "final_enemy_power_min": 90,
      "final_enemy_power_max": 180,
      "spike": "primeira_spell"
    },
    {
      "id": "s1_d01_aprendiz",
      "display_name": "Aprendiz",
      "rank": 1,
      "recommended_level_min": 5,
      "recommended_level_max": 7,
      "recommended_power_min": 260,
      "recommended_power_max": 650,
      "final_enemy_power_min": 250,
      "final_enemy_power_max": 520,
      "spike": "spell_basica_estavel"
    },
    {
      "id": "s1_d02_iniciado",
      "display_name": "Iniciado",
      "rank": 2,
      "recommended_level_min": 8,
      "recommended_level_max": 10,
      "recommended_power_min": 650,
      "recommended_power_max": 1300,
      "final_enemy_power_min": 650,
      "final_enemy_power_max": 1450,
      "spike": "pre_passiva"
    },
    {
      "id": "s1_d03_adepto",
      "display_name": "Adepto",
      "rank": 3,
      "recommended_level_min": 11,
      "recommended_level_max": 14,
      "recommended_power_min": 1300,
      "recommended_power_max": 1900,
      "final_enemy_power_min": 1500,
      "final_enemy_power_max": 2200,
      "spike": "passiva_ativa"
    },
    {
      "id": "s1_d04_familiar",
      "display_name": "Familiar",
      "rank": 4,
      "recommended_level_min": 15,
      "recommended_level_max": 19,
      "recommended_power_min": 1900,
      "recommended_power_max": 3300,
      "final_enemy_power_min": 2200,
      "final_enemy_power_max": 3600,
      "spike": "familiar"
    },
    {
      "id": "s1_d05_arcano",
      "display_name": "Arcano",
      "rank": 5,
      "recommended_level_min": 20,
      "recommended_level_max": 24,
      "recommended_power_min": 3300,
      "recommended_power_max": 5200,
      "final_enemy_power_min": 3800,
      "final_enemy_power_max": 5500,
      "spike": "build_madura"
    },
    {
      "id": "s1_d06_evocador",
      "display_name": "Evocador",
      "rank": 6,
      "recommended_level_min": 25,
      "recommended_level_max": 29,
      "recommended_power_min": 5200,
      "recommended_power_max": 7800,
      "final_enemy_power_min": 6000,
      "final_enemy_power_max": 8000,
      "spike": "spells_avancadas"
    },
    {
      "id": "s1_d07_mestre",
      "display_name": "Mestre",
      "rank": 7,
      "recommended_level_min": 30,
      "recommended_level_max": 34,
      "recommended_power_min": 7800,
      "recommended_power_max": 10500,
      "final_enemy_power_min": 8500,
      "final_enemy_power_max": 10800,
      "spike": "upgrades_altos"
    },
    {
      "id": "s1_d08_abissal",
      "display_name": "Abissal",
      "rank": 8,
      "recommended_level_min": 35,
      "recommended_level_max": 38,
      "recommended_power_min": 10500,
      "recommended_power_max": 13000,
      "final_enemy_power_min": 11000,
      "final_enemy_power_max": 13200,
      "spike": "aproximacao_cap"
    },
    {
      "id": "s1_d09_capstone",
      "display_name": "Capstone",
      "rank": 9,
      "recommended_level_min": 39,
      "recommended_level_max": 40,
      "recommended_power_min": 13000,
      "recommended_power_max": 14500,
      "final_enemy_power_min": 13500,
      "final_enemy_power_max": 15000,
      "spike": "fim_s1"
    }
  ],
  "difficulty_tiers": [
    {
      "id": "arena_tutorial_cinzas__s1_d00_intro",
      "display_name": "Tutorial: Cinzas Do Refugio - Intro",
      "description": "Primeiro duelo de tutorial, quase garantido.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "difficulty",
        "tutorial",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "season_id": "season_001",
      "arena_id": "arena_tutorial_cinzas",
      "difficulty_id": "s1_d00_intro",
      "difficulty_rank": 0,
      "recommended_level_min": 1,
      "recommended_level_max": 3,
      "recommended_power_min": 80,
      "recommended_power_max": 180,
      "enemy_sequence_id": "seq_tutorial",
      "enemy_sequence": [
        "pve_aprendiz_cinzas"
      ],
      "final_enemy_power": 90,
      "duel_power_targets": [
        90
      ],
      "reward_profile_id": "reward_s1_1d_d00",
      "clear_rate_target_min_percent": 95,
      "clear_rate_target_max_percent": 99
    },
    {
      "id": "arena_cinzas_curta__s1_d00_intro",
      "display_name": "Arena Curta Das Cinzas - Intro",
      "description": "Primeira arena real ainda guiada, com tres duelos confortaveis.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "difficulty",
        "three_duels",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "season_id": "season_001",
      "arena_id": "arena_cinzas_curta",
      "difficulty_id": "s1_d00_intro",
      "difficulty_rank": 0,
      "recommended_level_min": 3,
      "recommended_level_max": 4,
      "recommended_power_min": 160,
      "recommended_power_max": 260,
      "enemy_sequence_id": "seq_3_basic",
      "enemy_sequence": [
        "pve_aprendiz_cinzas",
        "pve_guardiao_barreira",
        "pve_sussurrador_veu"
      ],
      "final_enemy_power": 180,
      "duel_power_targets": [
        130,
        158,
        180
      ],
      "reward_profile_id": "reward_s1_3d_d00",
      "clear_rate_target_min_percent": 85,
      "clear_rate_target_max_percent": 92
    },
    {
      "id": "arena_cinzas_curta__s1_d01_aprendiz",
      "display_name": "Arena Curta Das Cinzas - Aprendiz",
      "description": "Primeira repeticao com pressao maior, ainda com conclusao confortavel.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "difficulty",
        "three_duels",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "season_id": "season_001",
      "arena_id": "arena_cinzas_curta",
      "difficulty_id": "s1_d01_aprendiz",
      "difficulty_rank": 1,
      "recommended_level_min": 5,
      "recommended_level_max": 6,
      "recommended_power_min": 280,
      "recommended_power_max": 470,
      "enemy_sequence_id": "seq_3_basic",
      "enemy_sequence": [
        "pve_aprendiz_cinzas",
        "pve_guardiao_barreira",
        "pve_sussurrador_veu"
      ],
      "final_enemy_power": 380,
      "duel_power_targets": [
        274,
        334,
        380
      ],
      "reward_profile_id": "reward_s1_3d_d01",
      "clear_rate_target_min_percent": 75,
      "clear_rate_target_max_percent": 85
    },
    {
      "id": "arena_cinzas_curta__s1_d02_iniciado",
      "display_name": "Arena Curta Das Cinzas - Iniciado",
      "description": "Arena curta para testar o primeiro unlock de spells de level 7.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "difficulty",
        "three_duels",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "season_id": "season_001",
      "arena_id": "arena_cinzas_curta",
      "difficulty_id": "s1_d02_iniciado",
      "difficulty_rank": 2,
      "recommended_level_min": 7,
      "recommended_level_max": 9,
      "recommended_power_min": 550,
      "recommended_power_max": 900,
      "enemy_sequence_id": "seq_3_basic",
      "enemy_sequence": [
        "pve_aprendiz_cinzas",
        "pve_guardiao_barreira",
        "pve_sussurrador_veu"
      ],
      "final_enemy_power": 750,
      "duel_power_targets": [
        540,
        660,
        750
      ],
      "reward_profile_id": "reward_s1_3d_d02",
      "clear_rate_target_min_percent": 60,
      "clear_rate_target_max_percent": 72
    },
    {
      "id": "arena_cinzas_curta__s1_d03_adepto",
      "display_name": "Arena Curta Das Cinzas - Adepto",
      "description": "Arena curta de pressao para jogador com Doutrina inicial.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "difficulty",
        "three_duels",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "season_id": "season_001",
      "arena_id": "arena_cinzas_curta",
      "difficulty_id": "s1_d03_adepto",
      "difficulty_rank": 3,
      "recommended_level_min": 10,
      "recommended_level_max": 12,
      "recommended_power_min": 1100,
      "recommended_power_max": 1550,
      "enemy_sequence_id": "seq_3_pressure",
      "enemy_sequence": [
        "pve_guardiao_barreira",
        "pve_pressao_veneno",
        "pve_misturador_elemental"
      ],
      "final_enemy_power": 1400,
      "duel_power_targets": [
        1008,
        1232,
        1400
      ],
      "reward_profile_id": "reward_s1_3d_d03",
      "clear_rate_target_min_percent": 50,
      "clear_rate_target_max_percent": 62
    },
    {
      "id": "arena_cinzas_curta__s1_d04_familiar",
      "display_name": "Arena Curta Das Cinzas - Familiar",
      "description": "Arena curta relevante no momento de desbloqueio do Familiar.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "difficulty",
        "three_duels",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "season_id": "season_001",
      "arena_id": "arena_cinzas_curta",
      "difficulty_id": "s1_d04_familiar",
      "difficulty_rank": 4,
      "recommended_level_min": 15,
      "recommended_level_max": 17,
      "recommended_power_min": 2000,
      "recommended_power_max": 2700,
      "enemy_sequence_id": "seq_3_pressure",
      "enemy_sequence": [
        "pve_guardiao_barreira",
        "pve_pressao_veneno",
        "pve_misturador_elemental"
      ],
      "final_enemy_power": 2400,
      "duel_power_targets": [
        1728,
        2112,
        2400
      ],
      "reward_profile_id": "reward_s1_3d_d04",
      "clear_rate_target_min_percent": 40,
      "clear_rate_target_max_percent": 52
    },
    {
      "id": "arena_cinzas_curta__s1_d05_arcano",
      "display_name": "Arena Curta Das Cinzas - Arcano",
      "description": "Arena curta de farm tecnico para build madura inicial.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "difficulty",
        "three_duels",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "season_id": "season_001",
      "arena_id": "arena_cinzas_curta",
      "difficulty_id": "s1_d05_arcano",
      "difficulty_rank": 5,
      "recommended_level_min": 20,
      "recommended_level_max": 22,
      "recommended_power_min": 3400,
      "recommended_power_max": 4300,
      "enemy_sequence_id": "seq_3_late",
      "enemy_sequence": [
        "pve_condutor_familiar",
        "pve_defensor_abissal",
        "pve_finalizador_abissal"
      ],
      "final_enemy_power": 3900,
      "duel_power_targets": [
        2808,
        3432,
        3900
      ],
      "reward_profile_id": "reward_s1_3d_d05",
      "clear_rate_target_min_percent": 34,
      "clear_rate_target_max_percent": 45
    },
    {
      "id": "arena_cinzas_curta__s1_d06_evocador",
      "display_name": "Arena Curta Das Cinzas - Evocador",
      "description": "Arena curta para jogadores com spells avancadas recem-abertas.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "difficulty",
        "three_duels",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "season_id": "season_001",
      "arena_id": "arena_cinzas_curta",
      "difficulty_id": "s1_d06_evocador",
      "difficulty_rank": 6,
      "recommended_level_min": 25,
      "recommended_level_max": 27,
      "recommended_power_min": 5400,
      "recommended_power_max": 6500,
      "enemy_sequence_id": "seq_3_late",
      "enemy_sequence": [
        "pve_condutor_familiar",
        "pve_defensor_abissal",
        "pve_finalizador_abissal"
      ],
      "final_enemy_power": 6000,
      "duel_power_targets": [
        4320,
        5280,
        6000
      ],
      "reward_profile_id": "reward_s1_3d_d06",
      "clear_rate_target_min_percent": 28,
      "clear_rate_target_max_percent": 38
    },
    {
      "id": "arena_cinzas_curta__s1_d07_mestre",
      "display_name": "Arena Curta Das Cinzas - Mestre",
      "description": "Arena curta late S1 para sessoes rapidas de risco moderado.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "difficulty",
        "three_duels",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "season_id": "season_001",
      "arena_id": "arena_cinzas_curta",
      "difficulty_id": "s1_d07_mestre",
      "difficulty_rank": 7,
      "recommended_level_min": 30,
      "recommended_level_max": 32,
      "recommended_power_min": 7800,
      "recommended_power_max": 9200,
      "enemy_sequence_id": "seq_3_late",
      "enemy_sequence": [
        "pve_condutor_familiar",
        "pve_defensor_abissal",
        "pve_finalizador_abissal"
      ],
      "final_enemy_power": 8500,
      "duel_power_targets": [
        6120,
        7480,
        8500
      ],
      "reward_profile_id": "reward_s1_3d_d07",
      "clear_rate_target_min_percent": 35,
      "clear_rate_target_max_percent": 40
    },
    {
      "id": "arena_cinzas_curta__s1_d08_abissal",
      "display_name": "Arena Curta Das Cinzas - Abissal",
      "description": "Arena curta de alta dificuldade perto do cap da Season 1.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "difficulty",
        "three_duels",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "season_id": "season_001",
      "arena_id": "arena_cinzas_curta",
      "difficulty_id": "s1_d08_abissal",
      "difficulty_rank": 8,
      "recommended_level_min": 35,
      "recommended_level_max": 37,
      "recommended_power_min": 10500,
      "recommended_power_max": 12000,
      "enemy_sequence_id": "seq_3_late",
      "enemy_sequence": [
        "pve_condutor_familiar",
        "pve_defensor_abissal",
        "pve_finalizador_abissal"
      ],
      "final_enemy_power": 11000,
      "duel_power_targets": [
        7920,
        9680,
        11000
      ],
      "reward_profile_id": "reward_s1_3d_d08",
      "clear_rate_target_min_percent": 35,
      "clear_rate_target_max_percent": 38
    },
    {
      "id": "arena_veu_curta__s1_d02_iniciado",
      "display_name": "Arena Do Veu - Iniciado",
      "description": "Primeira arena de quatro duelos para testar buffs e comportamento.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "difficulty",
        "four_duels",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "season_id": "season_001",
      "arena_id": "arena_veu_curta",
      "difficulty_id": "s1_d02_iniciado",
      "difficulty_rank": 2,
      "recommended_level_min": 8,
      "recommended_level_max": 10,
      "recommended_power_min": 700,
      "recommended_power_max": 1300,
      "enemy_sequence_id": "seq_4_basic",
      "enemy_sequence": [
        "pve_sussurrador_veu",
        "pve_pressao_veneno",
        "pve_guardiao_barreira",
        "pve_misturador_elemental"
      ],
      "final_enemy_power": 1200,
      "duel_power_targets": [
        780,
        936,
        1080,
        1200
      ],
      "reward_profile_id": "reward_s1_4d_d02",
      "clear_rate_target_min_percent": 55,
      "clear_rate_target_max_percent": 68
    },
    {
      "id": "arena_veu_curta__s1_d03_adepto",
      "display_name": "Arena Do Veu - Adepto",
      "description": "Arena de quatro duelos para jogador com Doutrina inicial.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "difficulty",
        "four_duels",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "season_id": "season_001",
      "arena_id": "arena_veu_curta",
      "difficulty_id": "s1_d03_adepto",
      "difficulty_rank": 3,
      "recommended_level_min": 11,
      "recommended_level_max": 14,
      "recommended_power_min": 1300,
      "recommended_power_max": 1900,
      "enemy_sequence_id": "seq_4_basic",
      "enemy_sequence": [
        "pve_sussurrador_veu",
        "pve_pressao_veneno",
        "pve_guardiao_barreira",
        "pve_misturador_elemental"
      ],
      "final_enemy_power": 1800,
      "duel_power_targets": [
        1170,
        1404,
        1620,
        1800
      ],
      "reward_profile_id": "reward_s1_4d_d03",
      "clear_rate_target_min_percent": 45,
      "clear_rate_target_max_percent": 58
    },
    {
      "id": "arena_veu_curta__s1_d04_familiar",
      "display_name": "Arena Do Veu - Familiar",
      "description": "Arena de quatro duelos para estabilizar Familiar e buffs acumulados.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "difficulty",
        "four_duels",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "season_id": "season_001",
      "arena_id": "arena_veu_curta",
      "difficulty_id": "s1_d04_familiar",
      "difficulty_rank": 4,
      "recommended_level_min": 15,
      "recommended_level_max": 19,
      "recommended_power_min": 2000,
      "recommended_power_max": 3300,
      "enemy_sequence_id": "seq_4_basic",
      "enemy_sequence": [
        "pve_sussurrador_veu",
        "pve_pressao_veneno",
        "pve_guardiao_barreira",
        "pve_misturador_elemental"
      ],
      "final_enemy_power": 3000,
      "duel_power_targets": [
        1950,
        2340,
        2700,
        3000
      ],
      "reward_profile_id": "reward_s1_4d_d04",
      "clear_rate_target_min_percent": 35,
      "clear_rate_target_max_percent": 48
    },
    {
      "id": "arena_veu_curta__s1_d05_arcano",
      "display_name": "Arena Do Veu - Arcano",
      "description": "Arena de quatro duelos com sequencia late para build madura.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "difficulty",
        "four_duels",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "season_id": "season_001",
      "arena_id": "arena_veu_curta",
      "difficulty_id": "s1_d05_arcano",
      "difficulty_rank": 5,
      "recommended_level_min": 20,
      "recommended_level_max": 24,
      "recommended_power_min": 3400,
      "recommended_power_max": 5200,
      "enemy_sequence_id": "seq_4_late",
      "enemy_sequence": [
        "pve_pressao_veneno",
        "pve_condutor_familiar",
        "pve_defensor_abissal",
        "pve_finalizador_abissal"
      ],
      "final_enemy_power": 4800,
      "duel_power_targets": [
        3120,
        3744,
        4320,
        4800
      ],
      "reward_profile_id": "reward_s1_4d_d05",
      "clear_rate_target_min_percent": 28,
      "clear_rate_target_max_percent": 40
    },
    {
      "id": "arena_veu_curta__s1_d06_evocador",
      "display_name": "Arena Do Veu - Evocador",
      "description": "Arena de quatro duelos para spells avancadas e pressao late.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "difficulty",
        "four_duels",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "season_id": "season_001",
      "arena_id": "arena_veu_curta",
      "difficulty_id": "s1_d06_evocador",
      "difficulty_rank": 6,
      "recommended_level_min": 25,
      "recommended_level_max": 29,
      "recommended_power_min": 5500,
      "recommended_power_max": 7800,
      "enemy_sequence_id": "seq_4_late",
      "enemy_sequence": [
        "pve_pressao_veneno",
        "pve_condutor_familiar",
        "pve_defensor_abissal",
        "pve_finalizador_abissal"
      ],
      "final_enemy_power": 7200,
      "duel_power_targets": [
        4680,
        5616,
        6480,
        7200
      ],
      "reward_profile_id": "reward_s1_4d_d06",
      "clear_rate_target_min_percent": 22,
      "clear_rate_target_max_percent": 34
    },
    {
      "id": "arena_veu_curta__s1_d07_mestre",
      "display_name": "Arena Do Veu - Mestre",
      "description": "Arena de quatro duelos late S1 para jogadores de upgrades altos.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "difficulty",
        "four_duels",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "season_id": "season_001",
      "arena_id": "arena_veu_curta",
      "difficulty_id": "s1_d07_mestre",
      "difficulty_rank": 7,
      "recommended_level_min": 30,
      "recommended_level_max": 34,
      "recommended_power_min": 8000,
      "recommended_power_max": 10500,
      "enemy_sequence_id": "seq_4_late",
      "enemy_sequence": [
        "pve_pressao_veneno",
        "pve_condutor_familiar",
        "pve_defensor_abissal",
        "pve_finalizador_abissal"
      ],
      "final_enemy_power": 9800,
      "duel_power_targets": [
        6370,
        7644,
        8820,
        9800
      ],
      "reward_profile_id": "reward_s1_4d_d07",
      "clear_rate_target_min_percent": 18,
      "clear_rate_target_max_percent": 28
    },
    {
      "id": "arena_veu_curta__s1_d08_abissal",
      "display_name": "Arena Do Veu - Abissal",
      "description": "Arena de quatro duelos perto do cap S1.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "difficulty",
        "four_duels",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "season_id": "season_001",
      "arena_id": "arena_veu_curta",
      "difficulty_id": "s1_d08_abissal",
      "difficulty_rank": 8,
      "recommended_level_min": 35,
      "recommended_level_max": 38,
      "recommended_power_min": 10500,
      "recommended_power_max": 13000,
      "enemy_sequence_id": "seq_4_late",
      "enemy_sequence": [
        "pve_pressao_veneno",
        "pve_condutor_familiar",
        "pve_defensor_abissal",
        "pve_finalizador_abissal"
      ],
      "final_enemy_power": 12500,
      "duel_power_targets": [
        8125,
        9750,
        11250,
        12500
      ],
      "reward_profile_id": "reward_s1_4d_d08",
      "clear_rate_target_min_percent": 14,
      "clear_rate_target_max_percent": 22
    },
    {
      "id": "arena_ossos_media__s1_d04_familiar",
      "display_name": "Arena Da Tempestade - Familiar",
      "description": "Primeira arena de cinco duelos, aberta no spike de Familiar.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "difficulty",
        "five_duels",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "season_id": "season_001",
      "arena_id": "arena_ossos_media",
      "difficulty_id": "s1_d04_familiar",
      "difficulty_rank": 4,
      "recommended_level_min": 15,
      "recommended_level_max": 17,
      "recommended_power_min": 2100,
      "recommended_power_max": 3000,
      "enemy_sequence_id": "seq_5_familiar",
      "enemy_sequence": [
        "pve_guardiao_barreira",
        "pve_pressao_veneno",
        "pve_condutor_familiar",
        "pve_misturador_elemental",
        "pve_invocador_ossario"
      ],
      "final_enemy_power": 2800,
      "duel_power_targets": [
        1680,
        2016,
        2352,
        2632,
        2800
      ],
      "reward_profile_id": "reward_s1_5d_d04",
      "clear_rate_target_min_percent": 35,
      "clear_rate_target_max_percent": 48
    },
    {
      "id": "arena_ossos_media__s1_d05_arcano",
      "display_name": "Arena Da Tempestade - Arcano",
      "description": "Arena de cinco duelos como midgame inicial da Season 1.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "difficulty",
        "five_duels",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "season_id": "season_001",
      "arena_id": "arena_ossos_media",
      "difficulty_id": "s1_d05_arcano",
      "difficulty_rank": 5,
      "recommended_level_min": 20,
      "recommended_level_max": 24,
      "recommended_power_min": 3400,
      "recommended_power_max": 5200,
      "enemy_sequence_id": "seq_5_familiar",
      "enemy_sequence": [
        "pve_guardiao_barreira",
        "pve_pressao_veneno",
        "pve_condutor_familiar",
        "pve_misturador_elemental",
        "pve_invocador_ossario"
      ],
      "final_enemy_power": 5000,
      "duel_power_targets": [
        3000,
        3600,
        4200,
        4700,
        5000
      ],
      "reward_profile_id": "reward_s1_5d_d05",
      "clear_rate_target_min_percent": 25,
      "clear_rate_target_max_percent": 38
    },
    {
      "id": "arena_ossos_media__s1_d06_evocador",
      "display_name": "Arena Da Tempestade - Evocador",
      "description": "Arena de cinco duelos para spells avancadas e inimigos late.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "difficulty",
        "five_duels",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "season_id": "season_001",
      "arena_id": "arena_ossos_media",
      "difficulty_id": "s1_d06_evocador",
      "difficulty_rank": 6,
      "recommended_level_min": 25,
      "recommended_level_max": 29,
      "recommended_power_min": 5500,
      "recommended_power_max": 7800,
      "enemy_sequence_id": "seq_5_late",
      "enemy_sequence": [
        "pve_pressao_veneno",
        "pve_condutor_familiar",
        "pve_defensor_abissal",
        "pve_invocador_ossario",
        "pve_finalizador_abissal"
      ],
      "final_enemy_power": 7500,
      "duel_power_targets": [
        4500,
        5400,
        6300,
        7050,
        7500
      ],
      "reward_profile_id": "reward_s1_5d_d06",
      "clear_rate_target_min_percent": 20,
      "clear_rate_target_max_percent": 32
    },
    {
      "id": "arena_ossos_media__s1_d07_mestre",
      "display_name": "Arena Da Tempestade - Mestre",
      "description": "Arena de cinco duelos late S1.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "difficulty",
        "five_duels",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "season_id": "season_001",
      "arena_id": "arena_ossos_media",
      "difficulty_id": "s1_d07_mestre",
      "difficulty_rank": 7,
      "recommended_level_min": 30,
      "recommended_level_max": 34,
      "recommended_power_min": 8000,
      "recommended_power_max": 10500,
      "enemy_sequence_id": "seq_5_late",
      "enemy_sequence": [
        "pve_pressao_veneno",
        "pve_condutor_familiar",
        "pve_defensor_abissal",
        "pve_invocador_ossario",
        "pve_finalizador_abissal"
      ],
      "final_enemy_power": 10000,
      "duel_power_targets": [
        6000,
        7200,
        8400,
        9400,
        10000
      ],
      "reward_profile_id": "reward_s1_5d_d07",
      "clear_rate_target_min_percent": 15,
      "clear_rate_target_max_percent": 26
    },
    {
      "id": "arena_ossos_media__s1_d08_abissal",
      "display_name": "Arena Da Tempestade - Abissal",
      "description": "Arena de cinco duelos perto do cap.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "difficulty",
        "five_duels",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "season_id": "season_001",
      "arena_id": "arena_ossos_media",
      "difficulty_id": "s1_d08_abissal",
      "difficulty_rank": 8,
      "recommended_level_min": 35,
      "recommended_level_max": 38,
      "recommended_power_min": 10500,
      "recommended_power_max": 13000,
      "enemy_sequence_id": "seq_5_late",
      "enemy_sequence": [
        "pve_pressao_veneno",
        "pve_condutor_familiar",
        "pve_defensor_abissal",
        "pve_invocador_ossario",
        "pve_finalizador_abissal"
      ],
      "final_enemy_power": 12800,
      "duel_power_targets": [
        7680,
        9216,
        10752,
        12032,
        12800
      ],
      "reward_profile_id": "reward_s1_5d_d08",
      "clear_rate_target_min_percent": 12,
      "clear_rate_target_max_percent": 20
    },
    {
      "id": "arena_abismo_longa__s1_d05_arcano",
      "display_name": "Arena Longa Do Abismo - Arcano",
      "description": "Primeira arena de seis duelos, aspiracional no level 20-24.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "difficulty",
        "six_duels",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "season_id": "season_001",
      "arena_id": "arena_abismo_longa",
      "difficulty_id": "s1_d05_arcano",
      "difficulty_rank": 5,
      "recommended_level_min": 20,
      "recommended_level_max": 24,
      "recommended_power_min": 3400,
      "recommended_power_max": 5200,
      "enemy_sequence_id": "seq_6_cap",
      "enemy_sequence": [
        "pve_misturador_elemental",
        "pve_condutor_familiar",
        "pve_invocador_ossario",
        "pve_defensor_abissal",
        "pve_pressao_veneno",
        "pve_finalizador_abissal"
      ],
      "final_enemy_power": 5200,
      "duel_power_targets": [
        3016,
        3640,
        4160,
        4680,
        4992,
        5200
      ],
      "reward_profile_id": "reward_s1_6d_d05",
      "clear_rate_target_min_percent": 20,
      "clear_rate_target_max_percent": 32
    },
    {
      "id": "arena_abismo_longa__s1_d06_evocador",
      "display_name": "Arena Longa Do Abismo - Evocador",
      "description": "Arena de seis duelos para spells avancadas.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "difficulty",
        "six_duels",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "season_id": "season_001",
      "arena_id": "arena_abismo_longa",
      "difficulty_id": "s1_d06_evocador",
      "difficulty_rank": 6,
      "recommended_level_min": 25,
      "recommended_level_max": 29,
      "recommended_power_min": 5500,
      "recommended_power_max": 7800,
      "enemy_sequence_id": "seq_6_cap",
      "enemy_sequence": [
        "pve_misturador_elemental",
        "pve_condutor_familiar",
        "pve_invocador_ossario",
        "pve_defensor_abissal",
        "pve_pressao_veneno",
        "pve_finalizador_abissal"
      ],
      "final_enemy_power": 8000,
      "duel_power_targets": [
        4640,
        5600,
        6400,
        7200,
        7680,
        8000
      ],
      "reward_profile_id": "reward_s1_6d_d06",
      "clear_rate_target_min_percent": 16,
      "clear_rate_target_max_percent": 28
    },
    {
      "id": "arena_abismo_longa__s1_d07_mestre",
      "display_name": "Arena Longa Do Abismo - Mestre",
      "description": "Arena de seis duelos late S1 para upgrades altos.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "difficulty",
        "six_duels",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "season_id": "season_001",
      "arena_id": "arena_abismo_longa",
      "difficulty_id": "s1_d07_mestre",
      "difficulty_rank": 7,
      "recommended_level_min": 30,
      "recommended_level_max": 34,
      "recommended_power_min": 8000,
      "recommended_power_max": 10500,
      "enemy_sequence_id": "seq_6_cap",
      "enemy_sequence": [
        "pve_misturador_elemental",
        "pve_condutor_familiar",
        "pve_invocador_ossario",
        "pve_defensor_abissal",
        "pve_pressao_veneno",
        "pve_finalizador_abissal"
      ],
      "final_enemy_power": 10800,
      "duel_power_targets": [
        6264,
        7560,
        8640,
        9720,
        10368,
        10800
      ],
      "reward_profile_id": "reward_s1_6d_d07",
      "clear_rate_target_min_percent": 13,
      "clear_rate_target_max_percent": 23
    },
    {
      "id": "arena_abismo_longa__s1_d08_abissal",
      "display_name": "Arena Longa Do Abismo - Abissal",
      "description": "Arena de seis duelos perto do cap S1.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "difficulty",
        "six_duels",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "season_id": "season_001",
      "arena_id": "arena_abismo_longa",
      "difficulty_id": "s1_d08_abissal",
      "difficulty_rank": 8,
      "recommended_level_min": 35,
      "recommended_level_max": 38,
      "recommended_power_min": 10500,
      "recommended_power_max": 13000,
      "enemy_sequence_id": "seq_6_cap",
      "enemy_sequence": [
        "pve_misturador_elemental",
        "pve_condutor_familiar",
        "pve_invocador_ossario",
        "pve_defensor_abissal",
        "pve_pressao_veneno",
        "pve_finalizador_abissal"
      ],
      "final_enemy_power": 13200,
      "duel_power_targets": [
        7656,
        9240,
        10560,
        11880,
        12672,
        13200
      ],
      "reward_profile_id": "reward_s1_6d_d08",
      "clear_rate_target_min_percent": 10,
      "clear_rate_target_max_percent": 18
    },
    {
      "id": "arena_abismo_longa__s1_d09_capstone",
      "display_name": "Arena Longa Do Abismo - Capstone",
      "description": "Capstone de seis duelos para o fim da Season 1.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "difficulty",
        "six_duels",
        "capstone",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "season_id": "season_001",
      "arena_id": "arena_abismo_longa",
      "difficulty_id": "s1_d09_capstone",
      "difficulty_rank": 9,
      "recommended_level_min": 39,
      "recommended_level_max": 40,
      "recommended_power_min": 13000,
      "recommended_power_max": 14500,
      "enemy_sequence_id": "seq_6_cap",
      "enemy_sequence": [
        "pve_misturador_elemental",
        "pve_condutor_familiar",
        "pve_invocador_ossario",
        "pve_defensor_abissal",
        "pve_pressao_veneno",
        "pve_finalizador_abissal"
      ],
      "final_enemy_power": 15000,
      "duel_power_targets": [
        8700,
        10500,
        12000,
        13500,
        14400,
        15000
      ],
      "reward_profile_id": "reward_s1_6d_d09",
      "clear_rate_target_min_percent": 8,
      "clear_rate_target_max_percent": 14
    }
  ],
  "enemy_sequences": [
    {
      "id": "seq_tutorial",
      "enemy_ids": [
        "pve_aprendiz_cinzas"
      ]
    },
    {
      "id": "seq_3_basic",
      "enemy_ids": [
        "pve_aprendiz_cinzas",
        "pve_guardiao_barreira",
        "pve_sussurrador_veu"
      ]
    },
    {
      "id": "seq_3_pressure",
      "enemy_ids": [
        "pve_guardiao_barreira",
        "pve_pressao_veneno",
        "pve_misturador_elemental"
      ]
    },
    {
      "id": "seq_3_late",
      "enemy_ids": [
        "pve_condutor_familiar",
        "pve_defensor_abissal",
        "pve_finalizador_abissal"
      ]
    },
    {
      "id": "seq_4_basic",
      "enemy_ids": [
        "pve_sussurrador_veu",
        "pve_pressao_veneno",
        "pve_guardiao_barreira",
        "pve_misturador_elemental"
      ]
    },
    {
      "id": "seq_4_late",
      "enemy_ids": [
        "pve_pressao_veneno",
        "pve_condutor_familiar",
        "pve_defensor_abissal",
        "pve_finalizador_abissal"
      ]
    },
    {
      "id": "seq_5_familiar",
      "enemy_ids": [
        "pve_guardiao_barreira",
        "pve_pressao_veneno",
        "pve_condutor_familiar",
        "pve_misturador_elemental",
        "pve_invocador_ossario"
      ]
    },
    {
      "id": "seq_5_late",
      "enemy_ids": [
        "pve_pressao_veneno",
        "pve_condutor_familiar",
        "pve_defensor_abissal",
        "pve_invocador_ossario",
        "pve_finalizador_abissal"
      ]
    },
    {
      "id": "seq_6_cap",
      "enemy_ids": [
        "pve_misturador_elemental",
        "pve_condutor_familiar",
        "pve_invocador_ossario",
        "pve_defensor_abissal",
        "pve_pressao_veneno",
        "pve_finalizador_abissal"
      ]
    }
  ],
  "duel_power_distributions": {
    "1": [
      100
    ],
    "3": [
      72,
      88,
      100
    ],
    "4": [
      65,
      78,
      90,
      100
    ],
    "5": [
      60,
      72,
      84,
      94,
      100
    ],
    "6": [
      58,
      70,
      80,
      90,
      96,
      100
    ]
  },
  "enemies": [
    {
      "id": "pve_aprendiz_cinzas",
      "display_name": "Aprendiz de Cinzas",
      "description": "Inimigo tutorial de instrumento ritual simples, usado para ensinar o primeiro duelo.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "enemy",
        "tutorial",
        "starter_instrument"
      ],
      "mode": "PVE_ARENA_V1",
      "archetype": "starter_instrument",
      "teaching_goal": "basic_duel_readability",
      "target_level": 2,
      "target_power": 90,
      "power_band_id": "band_001",
      "source_bot_build_id": "bot_starter_instrument_01",
      "legal_unlocks": {
        "spell_slots": 0,
        "requires_doutrina": false,
        "requires_familiar": false
      },
      "presentation": {
        "portrait_asset_id": "portrait_training_bot",
        "subtitle": "Duelista iniciante"
      },
      "reward_tags": [
        "tutorial"
      ],
      "ranked": false
    },
    {
      "id": "pve_guardiao_barreira",
      "display_name": "Guardiao de Barreira",
      "description": "Defensor inicial que testa Guarda, barreira e duracao maior sem comportamento customizado.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "enemy",
        "defensive_occultist",
        "guard"
      ],
      "mode": "PVE_ARENA_V1",
      "archetype": "defensive_occultist",
      "teaching_goal": "defense_and_barrier_pressure",
      "target_level": 6,
      "target_power": 190,
      "power_band_id": "band_002",
      "source_bot_build_id": "bot_effect_trainer_01",
      "legal_unlocks": {
        "spell_slots": 1,
        "requires_doutrina": false,
        "requires_familiar": false
      },
      "presentation": {
        "portrait_asset_id": "portrait_training_bot",
        "subtitle": "Defensor ritual"
      },
      "reward_tags": [
        "defense_check"
      ],
      "ranked": false
    },
    {
      "id": "pve_sussurrador_veu",
      "display_name": "Sussurrador do Veu",
      "description": "Controlador mental inicial para ensinar pressao de Vontade e leitura de controle.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "enemy",
        "mental_controller"
      ],
      "mode": "PVE_ARENA_V1",
      "archetype": "mental_controller",
      "teaching_goal": "mental_control_intro",
      "target_level": 5,
      "target_power": 260,
      "power_band_id": "band_002",
      "source_bot_build_id": "bot_mental_controller_01",
      "legal_unlocks": {
        "spell_slots": 1,
        "requires_doutrina": false,
        "requires_familiar": false
      },
      "presentation": {
        "portrait_asset_id": "portrait_training_bot",
        "subtitle": "Controle mental"
      },
      "reward_tags": [
        "control_check"
      ],
      "ranked": false
    },
    {
      "id": "pve_misturador_elemental",
      "display_name": "Misturador Elemental",
      "description": "Inimigo de duas fontes elementais para testar resistencia, mana e resposta a burst moderado.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "enemy",
        "elemental_mixer"
      ],
      "mode": "PVE_ARENA_V1",
      "archetype": "elemental_mixer",
      "teaching_goal": "two_spell_pressure",
      "target_level": 14,
      "target_power": 720,
      "power_band_id": "band_003",
      "source_bot_build_id": "bot_elemental_mixer_01",
      "legal_unlocks": {
        "spell_slots": 2,
        "requires_doutrina": true,
        "requires_familiar": false
      },
      "presentation": {
        "portrait_asset_id": "portrait_training_bot",
        "subtitle": "Elementalista"
      },
      "reward_tags": [
        "elemental_check"
      ],
      "ranked": false
    },
    {
      "id": "pve_pressao_veneno",
      "display_name": "Pressao de Veneno",
      "description": "Inimigo de pressao por dano ao longo do tempo para validar Pocao e comportamento defensivo simples.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "enemy",
        "dot_pressure"
      ],
      "mode": "PVE_ARENA_V1",
      "archetype": "dot_pressure",
      "teaching_goal": "damage_over_time_response",
      "target_level": 8,
      "target_power": 360,
      "power_band_id": "band_002",
      "source_bot_build_id": "bot_effect_trainer_01",
      "legal_unlocks": {
        "spell_slots": 2,
        "requires_doutrina": false,
        "requires_familiar": false
      },
      "presentation": {
        "portrait_asset_id": "portrait_training_bot",
        "subtitle": "Pressao continua"
      },
      "reward_tags": [
        "dot_check"
      ],
      "ranked": false
    },
    {
      "id": "pve_condutor_familiar",
      "display_name": "Condutor de Familiar",
      "description": "Inimigo que introduz Familiar como fonte adicional de pressao depois do jogador entender arena curta.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "enemy",
        "familiar_handler"
      ],
      "mode": "PVE_ARENA_V1",
      "archetype": "familiar_handler",
      "teaching_goal": "familiar_pressure_intro",
      "target_level": 22,
      "target_power": 1320,
      "power_band_id": "band_004",
      "source_bot_build_id": "bot_familiar_handler_01",
      "legal_unlocks": {
        "spell_slots": 2,
        "requires_doutrina": true,
        "requires_familiar": true
      },
      "presentation": {
        "portrait_asset_id": "portrait_training_bot",
        "subtitle": "Familiar ativo"
      },
      "reward_tags": [
        "familiar_check"
      ],
      "ranked": false
    },
    {
      "id": "pve_invocador_ossario",
      "display_name": "Invocador Ossario",
      "description": "Inimigo avancado com summons para validar replay e pressao de alvos extras em arena media.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "enemy",
        "summoner"
      ],
      "mode": "PVE_ARENA_V1",
      "archetype": "summoner",
      "teaching_goal": "summon_pressure",
      "target_level": 35,
      "target_power": 2450,
      "power_band_id": "band_005",
      "source_bot_build_id": "bot_summoner_01",
      "legal_unlocks": {
        "spell_slots": 3,
        "requires_doutrina": true,
        "requires_familiar": true
      },
      "presentation": {
        "portrait_asset_id": "portrait_training_bot",
        "subtitle": "Invocador"
      },
      "reward_tags": [
        "summon_check"
      ],
      "ranked": false
    },
    {
      "id": "pve_defensor_abissal",
      "display_name": "Defensor Abissal",
      "description": "Check defensivo de arena longa, reutilizando build legal existente ate haver inimigos finalizados.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "enemy",
        "defensive_occultist",
        "initial_cap"
      ],
      "mode": "PVE_ARENA_V1",
      "archetype": "defensive_occultist",
      "teaching_goal": "long_arena_defense_check",
      "target_level": 28,
      "target_power": 1650,
      "power_band_id": "band_004",
      "source_bot_build_id": "bot_familiar_handler_01",
      "legal_unlocks": {
        "spell_slots": 2,
        "requires_doutrina": true,
        "requires_familiar": true
      },
      "presentation": {
        "portrait_asset_id": "portrait_training_bot",
        "subtitle": "Defesa abissal"
      },
      "reward_tags": [
        "long_arena_check"
      ],
      "ranked": false
    },
    {
      "id": "pve_finalizador_abissal",
      "display_name": "Finalizador Abissal",
      "description": "Finalizador do cap inicial de 6 duelos, focado em burst e pressao de summons sem nova regra customizada.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "enemy",
        "funeral_burst",
        "initial_cap"
      ],
      "mode": "PVE_ARENA_V1",
      "archetype": "funeral_burst",
      "teaching_goal": "initial_cap_finale",
      "target_level": 38,
      "target_power": 2700,
      "power_band_id": "band_005",
      "source_bot_build_id": "bot_summoner_01",
      "legal_unlocks": {
        "spell_slots": 3,
        "requires_doutrina": true,
        "requires_familiar": true
      },
      "presentation": {
        "portrait_asset_id": "portrait_training_bot",
        "subtitle": "Finalizador"
      },
      "reward_tags": [
        "capstone"
      ],
      "ranked": false
    }
  ],
  "buffs": [
    {
      "id": "arena_buff_vitalidade_menor",
      "display_name": "Vitalidade Menor",
      "description": "Aumenta levemente a vida maxima durante a tentativa de Arena PVE.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "buff",
        "stat",
        "max_hp"
      ],
      "mode": "PVE_ARENA_V1",
      "rarity": "common",
      "stat_modifiers": [
        {
          "stat": "max_hp",
          "operation": "add_percent",
          "value": 4
        }
      ],
      "stacking": "additive_within_attempt",
      "max_stacks": 5,
      "offer_weight": 1
    },
    {
      "id": "arena_buff_potencia_menor",
      "display_name": "Potencia Ritual Menor",
      "description": "Aumenta levemente a Potencia Ritual durante a tentativa de Arena PVE.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "buff",
        "stat",
        "ritual_power"
      ],
      "mode": "PVE_ARENA_V1",
      "rarity": "common",
      "stat_modifiers": [
        {
          "stat": "ritual_power",
          "operation": "add_percent",
          "value": 4
        }
      ],
      "stacking": "additive_within_attempt",
      "max_stacks": 5,
      "offer_weight": 1
    },
    {
      "id": "arena_buff_guarda_menor",
      "display_name": "Guarda Menor",
      "description": "Aumenta levemente a Guarda durante a tentativa de Arena PVE.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "buff",
        "stat",
        "guard"
      ],
      "mode": "PVE_ARENA_V1",
      "rarity": "common",
      "stat_modifiers": [
        {
          "stat": "guard",
          "operation": "add_percent",
          "value": 4
        }
      ],
      "stacking": "additive_within_attempt",
      "max_stacks": 5,
      "offer_weight": 1
    },
    {
      "id": "arena_buff_mana_menor",
      "display_name": "Mana Menor",
      "description": "Aumenta levemente a mana maxima durante a tentativa de Arena PVE.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "buff",
        "stat",
        "max_mana"
      ],
      "mode": "PVE_ARENA_V1",
      "rarity": "common",
      "stat_modifiers": [
        {
          "stat": "max_mana",
          "operation": "add_percent",
          "value": 4
        }
      ],
      "stacking": "additive_within_attempt",
      "max_stacks": 5,
      "offer_weight": 1
    },
    {
      "id": "arena_buff_regen_mana_menor",
      "display_name": "Regen De Mana Menor",
      "description": "Aumenta levemente a regeneracao de mana durante a tentativa de Arena PVE.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "buff",
        "stat",
        "mana_regen"
      ],
      "mode": "PVE_ARENA_V1",
      "rarity": "common",
      "stat_modifiers": [
        {
          "stat": "mana_regen",
          "operation": "add_percent",
          "value": 5
        }
      ],
      "stacking": "additive_within_attempt",
      "max_stacks": 5,
      "offer_weight": 1
    },
    {
      "id": "arena_buff_celeridade_menor",
      "display_name": "Celeridade Ritual Menor",
      "description": "Aumenta levemente a Celeridade Ritual durante a tentativa de Arena PVE.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "buff",
        "stat",
        "ritual_haste"
      ],
      "mode": "PVE_ARENA_V1",
      "rarity": "common",
      "stat_modifiers": [
        {
          "stat": "ritual_haste",
          "operation": "add_percent",
          "value": 3
        }
      ],
      "stacking": "additive_within_attempt",
      "max_stacks": 5,
      "offer_weight": 1
    },
    {
      "id": "arena_buff_vontade_menor",
      "display_name": "Vontade Menor",
      "description": "Aumenta levemente a Vontade durante a tentativa de Arena PVE.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "buff",
        "stat",
        "will"
      ],
      "mode": "PVE_ARENA_V1",
      "rarity": "common",
      "stat_modifiers": [
        {
          "stat": "will",
          "operation": "add_percent",
          "value": 4
        }
      ],
      "stacking": "additive_within_attempt",
      "max_stacks": 5,
      "offer_weight": 1
    },
    {
      "id": "arena_buff_controle_menor",
      "display_name": "Controle Ritual Menor",
      "description": "Aumenta levemente o Controle Ritual durante a tentativa de Arena PVE.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "buff",
        "stat",
        "ritual_control"
      ],
      "mode": "PVE_ARENA_V1",
      "rarity": "common",
      "stat_modifiers": [
        {
          "stat": "ritual_control",
          "operation": "add_percent",
          "value": 4
        }
      ],
      "stacking": "additive_within_attempt",
      "max_stacks": 5,
      "offer_weight": 1
    }
  ],
  "rewards": [
    {
      "id": "arena_tutorial_clear",
      "display_name": "Clear Tutorial Arena",
      "description": "Recompensa calibravel da primeira arena tutorial de 1 duelo.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "reward",
        "tutorial",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 35,
        "almas": 2,
        "energia": 2,
        "ossos": 20
      },
      "first_clear_multiplier": 1.5,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.25,
      "record_bonus": {
        "xp": 10
      },
      "daily_bonus_key": "arena_daily_first_clear",
      "weekly_cap_key": "arena_weekly_participation",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "arena_3_duel_clear_d1",
      "display_name": "Clear Arena 3 Duels D1",
      "description": "Recompensa calibravel para concluir a primeira arena real de 3 duelos.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "reward",
        "three_duels",
        "difficulty_1",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 90,
        "almas": 6,
        "energia": 4,
        "sangue": 1,
        "ossos": 60
      },
      "first_clear_multiplier": 1.6,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.35,
      "record_bonus": {
        "xp": 20,
        "almas": 1
      },
      "daily_bonus_key": "arena_daily_first_three_duel_clear",
      "weekly_cap_key": "arena_weekly_participation",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "arena_4_duel_clear_d2",
      "display_name": "Clear Arena 4 Duels D2",
      "description": "Recompensa calibravel para concluir uma arena de 4 duelos de dificuldade 2.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "reward",
        "four_duels",
        "difficulty_2",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 120,
        "almas": 8,
        "energia": 5,
        "sangue": 2,
        "ossos": 90
      },
      "first_clear_multiplier": 1.6,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.35,
      "record_bonus": {
        "xp": 25,
        "almas": 1
      },
      "daily_bonus_key": "arena_daily_first_three_duel_clear",
      "weekly_cap_key": "arena_weekly_participation",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "arena_5_duel_clear_d3",
      "display_name": "Clear Arena 5 Duels D3",
      "description": "Recompensa calibravel para a primeira arena longa de 5 duelos.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "reward",
        "five_duels",
        "difficulty_3",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 170,
        "almas": 11,
        "energia": 7,
        "sangue": 3,
        "cristais": 1,
        "ossos": 130
      },
      "first_clear_multiplier": 1.7,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.3,
      "record_bonus": {
        "xp": 35,
        "almas": 2
      },
      "daily_bonus_key": "arena_daily_longer_clear",
      "weekly_cap_key": "arena_weekly_mastery",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "arena_6_duel_clear_d4",
      "display_name": "Clear Arena 6 Duels D4",
      "description": "Recompensa calibravel para o cap inicial de 6 duelos.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "reward",
        "six_duels",
        "difficulty_4",
        "initial_cap",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 230,
        "almas": 15,
        "energia": 10,
        "sangue": 4,
        "cristais": 2,
        "ossos": 180
      },
      "first_clear_multiplier": 1.8,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.25,
      "record_bonus": {
        "xp": 50,
        "almas": 3
      },
      "daily_bonus_key": "arena_daily_longer_clear",
      "weekly_cap_key": "arena_weekly_mastery",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "reward_s1_1d_d00",
      "display_name": "Season 1 1D D00 Clear",
      "description": "Perfil calibravel Season 1 para concluir arena PVE de 1 duelo na dificuldade rank 0.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "reward",
        "tutorial",
        "difficulty_0",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 40,
        "almas": 2,
        "energia": 2,
        "ossos": 41
      },
      "first_clear_multiplier": 1.5,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.25,
      "record_bonus": {
        "xp": 7,
        "almas": 0
      },
      "daily_bonus_key": "arena_daily_short_clear",
      "weekly_cap_key": "arena_weekly_participation",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "reward_s1_3d_d00",
      "display_name": "Season 1 3D D00 Clear",
      "description": "Perfil calibravel Season 1 para concluir arena PVE de 3 duelos na dificuldade rank 0.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "reward",
        "three_duels",
        "difficulty_0",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 90,
        "almas": 6,
        "energia": 3,
        "ossos": 104
      },
      "first_clear_multiplier": 1.6,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.35,
      "record_bonus": {
        "xp": 16,
        "almas": 0
      },
      "daily_bonus_key": "arena_daily_short_clear",
      "weekly_cap_key": "arena_weekly_participation",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "reward_s1_3d_d01",
      "display_name": "Season 1 3D D01 Clear",
      "description": "Perfil calibravel Season 1 para concluir arena PVE de 3 duelos na dificuldade rank 1.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "reward",
        "three_duels",
        "difficulty_1",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 120,
        "almas": 9,
        "energia": 5,
        "ossos": 131
      },
      "first_clear_multiplier": 1.6,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.35,
      "record_bonus": {
        "xp": 22,
        "almas": 1
      },
      "daily_bonus_key": "arena_daily_short_clear",
      "weekly_cap_key": "arena_weekly_participation",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "reward_s1_3d_d02",
      "display_name": "Season 1 3D D02 Clear",
      "description": "Perfil calibravel Season 1 para concluir arena PVE de 3 duelos na dificuldade rank 2.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "reward",
        "three_duels",
        "difficulty_2",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 160,
        "almas": 11,
        "energia": 6,
        "sangue": 1,
        "ossos": 165
      },
      "first_clear_multiplier": 1.6,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.35,
      "record_bonus": {
        "xp": 29,
        "almas": 1
      },
      "daily_bonus_key": "arena_daily_short_clear",
      "weekly_cap_key": "arena_weekly_participation",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "reward_s1_3d_d03",
      "display_name": "Season 1 3D D03 Clear",
      "description": "Perfil calibravel Season 1 para concluir arena PVE de 3 duelos na dificuldade rank 3.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "reward",
        "three_duels",
        "difficulty_3",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 210,
        "almas": 14,
        "energia": 7,
        "sangue": 1,
        "ossos": 206
      },
      "first_clear_multiplier": 1.6,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.3,
      "record_bonus": {
        "xp": 38,
        "almas": 2
      },
      "daily_bonus_key": "arena_daily_short_clear",
      "weekly_cap_key": "arena_weekly_participation",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "reward_s1_3d_d04",
      "display_name": "Season 1 3D D04 Clear",
      "description": "Perfil calibravel Season 1 para concluir arena PVE de 3 duelos na dificuldade rank 4.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "reward",
        "three_duels",
        "difficulty_4",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 275,
        "almas": 17,
        "energia": 9,
        "sangue": 2,
        "ossos": 256,
        "po_osso": 1
      },
      "first_clear_multiplier": 1.6,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.3,
      "record_bonus": {
        "xp": 50,
        "almas": 2
      },
      "daily_bonus_key": "arena_daily_short_clear",
      "weekly_cap_key": "arena_weekly_participation",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "reward_s1_3d_d05",
      "display_name": "Season 1 3D D05 Clear",
      "description": "Perfil calibravel Season 1 para concluir arena PVE de 3 duelos na dificuldade rank 5.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "reward",
        "three_duels",
        "difficulty_5",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 350,
        "almas": 20,
        "energia": 10,
        "sangue": 3,
        "ossos": 313,
        "po_osso": 2
      },
      "first_clear_multiplier": 1.6,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.3,
      "record_bonus": {
        "xp": 63,
        "almas": 3
      },
      "daily_bonus_key": "arena_daily_short_clear",
      "weekly_cap_key": "arena_weekly_participation",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "reward_s1_3d_d06",
      "display_name": "Season 1 3D D06 Clear",
      "description": "Perfil calibravel Season 1 para concluir arena PVE de 3 duelos na dificuldade rank 6.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "reward",
        "three_duels",
        "difficulty_6",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 450,
        "almas": 22,
        "energia": 11,
        "sangue": 3,
        "cristais": 1,
        "ossos": 386,
        "po_osso": 3
      },
      "first_clear_multiplier": 1.6,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.25,
      "record_bonus": {
        "xp": 81,
        "almas": 3
      },
      "daily_bonus_key": "arena_daily_short_clear",
      "weekly_cap_key": "arena_weekly_participation",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "reward_s1_3d_d07",
      "display_name": "Season 1 3D D07 Clear",
      "description": "Perfil calibravel Season 1 para concluir arena PVE de 3 duelos na dificuldade rank 7.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "reward",
        "three_duels",
        "difficulty_7",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 570,
        "almas": 25,
        "energia": 13,
        "sangue": 4,
        "cristais": 1,
        "ossos": 472,
        "po_osso": 4
      },
      "first_clear_multiplier": 1.6,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.25,
      "record_bonus": {
        "xp": 103,
        "almas": 3
      },
      "daily_bonus_key": "arena_daily_short_clear",
      "weekly_cap_key": "arena_weekly_participation",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "reward_s1_3d_d08",
      "display_name": "Season 1 3D D08 Clear",
      "description": "Perfil calibravel Season 1 para concluir arena PVE de 3 duelos na dificuldade rank 8.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "reward",
        "three_duels",
        "difficulty_8",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 710,
        "almas": 28,
        "energia": 14,
        "sangue": 5,
        "cristais": 2,
        "ossos": 571,
        "po_osso": 5
      },
      "first_clear_multiplier": 1.6,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.25,
      "record_bonus": {
        "xp": 128,
        "almas": 4
      },
      "daily_bonus_key": "arena_daily_short_clear",
      "weekly_cap_key": "arena_weekly_participation",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "reward_s1_4d_d02",
      "display_name": "Season 1 4D D02 Clear",
      "description": "Perfil calibravel Season 1 para concluir arena PVE de 4 duelos na dificuldade rank 2.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "reward",
        "four_duels",
        "difficulty_2",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 160,
        "almas": 15,
        "energia": 8,
        "sangue": 1,
        "ossos": 180
      },
      "first_clear_multiplier": 1.6,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.35,
      "record_bonus": {
        "xp": 29,
        "almas": 2
      },
      "daily_bonus_key": "arena_daily_longer_clear",
      "weekly_cap_key": "arena_weekly_participation",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "reward_s1_4d_d03",
      "display_name": "Season 1 4D D03 Clear",
      "description": "Perfil calibravel Season 1 para concluir arena PVE de 4 duelos na dificuldade rank 3.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "reward",
        "four_duels",
        "difficulty_3",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 220,
        "almas": 19,
        "energia": 10,
        "sangue": 2,
        "ossos": 227
      },
      "first_clear_multiplier": 1.6,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.3,
      "record_bonus": {
        "xp": 40,
        "almas": 2
      },
      "daily_bonus_key": "arena_daily_longer_clear",
      "weekly_cap_key": "arena_weekly_participation",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "reward_s1_4d_d04",
      "display_name": "Season 1 4D D04 Clear",
      "description": "Perfil calibravel Season 1 para concluir arena PVE de 4 duelos na dificuldade rank 4.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "reward",
        "four_duels",
        "difficulty_4",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 295,
        "almas": 22,
        "energia": 12,
        "sangue": 3,
        "ossos": 284,
        "po_osso": 1
      },
      "first_clear_multiplier": 1.6,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.3,
      "record_bonus": {
        "xp": 53,
        "almas": 3
      },
      "daily_bonus_key": "arena_daily_longer_clear",
      "weekly_cap_key": "arena_weekly_participation",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "reward_s1_4d_d05",
      "display_name": "Season 1 4D D05 Clear",
      "description": "Perfil calibravel Season 1 para concluir arena PVE de 4 duelos na dificuldade rank 5.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "reward",
        "four_duels",
        "difficulty_5",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 400,
        "almas": 26,
        "energia": 13,
        "sangue": 4,
        "ossos": 360,
        "po_osso": 2
      },
      "first_clear_multiplier": 1.6,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.3,
      "record_bonus": {
        "xp": 72,
        "almas": 3
      },
      "daily_bonus_key": "arena_daily_longer_clear",
      "weekly_cap_key": "arena_weekly_participation",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "reward_s1_4d_d06",
      "display_name": "Season 1 4D D06 Clear",
      "description": "Perfil calibravel Season 1 para concluir arena PVE de 4 duelos na dificuldade rank 6.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "reward",
        "four_duels",
        "difficulty_6",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 530,
        "almas": 30,
        "energia": 15,
        "sangue": 5,
        "cristais": 1,
        "ossos": 453,
        "po_osso": 4
      },
      "first_clear_multiplier": 1.6,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.25,
      "record_bonus": {
        "xp": 95,
        "almas": 4
      },
      "daily_bonus_key": "arena_daily_longer_clear",
      "weekly_cap_key": "arena_weekly_participation",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "reward_s1_4d_d07",
      "display_name": "Season 1 4D D07 Clear",
      "description": "Perfil calibravel Season 1 para concluir arena PVE de 4 duelos na dificuldade rank 7.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "reward",
        "four_duels",
        "difficulty_7",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 690,
        "almas": 33,
        "energia": 17,
        "sangue": 6,
        "cristais": 2,
        "ossos": 565,
        "po_osso": 5
      },
      "first_clear_multiplier": 1.6,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.25,
      "record_bonus": {
        "xp": 124,
        "almas": 4
      },
      "daily_bonus_key": "arena_daily_longer_clear",
      "weekly_cap_key": "arena_weekly_participation",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "reward_s1_4d_d08",
      "display_name": "Season 1 4D D08 Clear",
      "description": "Perfil calibravel Season 1 para concluir arena PVE de 4 duelos na dificuldade rank 8.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "reward",
        "four_duels",
        "difficulty_8",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 880,
        "almas": 37,
        "energia": 19,
        "sangue": 7,
        "cristais": 3,
        "ossos": 696,
        "po_osso": 6
      },
      "first_clear_multiplier": 1.6,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.25,
      "record_bonus": {
        "xp": 158,
        "almas": 5
      },
      "daily_bonus_key": "arena_daily_longer_clear",
      "weekly_cap_key": "arena_weekly_participation",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "reward_s1_5d_d04",
      "display_name": "Season 1 5D D04 Clear",
      "description": "Perfil calibravel Season 1 para concluir arena PVE de 5 duelos na dificuldade rank 4.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "reward",
        "five_duels",
        "difficulty_4",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 300,
        "almas": 28,
        "energia": 15,
        "sangue": 3,
        "ossos": 302,
        "po_osso": 1
      },
      "first_clear_multiplier": 1.7,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.3,
      "record_bonus": {
        "xp": 54,
        "almas": 4
      },
      "daily_bonus_key": "arena_daily_longer_clear",
      "weekly_cap_key": "arena_weekly_mastery",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "reward_s1_5d_d05",
      "display_name": "Season 1 5D D05 Clear",
      "description": "Perfil calibravel Season 1 para concluir arena PVE de 5 duelos na dificuldade rank 5.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "reward",
        "five_duels",
        "difficulty_5",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 440,
        "almas": 33,
        "energia": 17,
        "sangue": 5,
        "cristais": 1,
        "ossos": 401,
        "po_osso": 3
      },
      "first_clear_multiplier": 1.7,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.3,
      "record_bonus": {
        "xp": 79,
        "almas": 4
      },
      "daily_bonus_key": "arena_daily_longer_clear",
      "weekly_cap_key": "arena_weekly_mastery",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "reward_s1_5d_d06",
      "display_name": "Season 1 5D D06 Clear",
      "description": "Perfil calibravel Season 1 para concluir arena PVE de 5 duelos na dificuldade rank 6.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "reward",
        "five_duels",
        "difficulty_6",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 620,
        "almas": 37,
        "energia": 19,
        "sangue": 6,
        "cristais": 2,
        "ossos": 526,
        "po_osso": 5
      },
      "first_clear_multiplier": 1.7,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.25,
      "record_bonus": {
        "xp": 112,
        "almas": 5
      },
      "daily_bonus_key": "arena_daily_longer_clear",
      "weekly_cap_key": "arena_weekly_mastery",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "reward_s1_5d_d07",
      "display_name": "Season 1 5D D07 Clear",
      "description": "Perfil calibravel Season 1 para concluir arena PVE de 5 duelos na dificuldade rank 7.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "reward",
        "five_duels",
        "difficulty_7",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 860,
        "almas": 42,
        "energia": 21,
        "sangue": 7,
        "cristais": 3,
        "ossos": 690,
        "po_osso": 6
      },
      "first_clear_multiplier": 1.7,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.25,
      "record_bonus": {
        "xp": 155,
        "almas": 6
      },
      "daily_bonus_key": "arena_daily_longer_clear",
      "weekly_cap_key": "arena_weekly_mastery",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "reward_s1_5d_d08",
      "display_name": "Season 1 5D D08 Clear",
      "description": "Perfil calibravel Season 1 para concluir arena PVE de 5 duelos na dificuldade rank 8.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "reward",
        "five_duels",
        "difficulty_8",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 1150,
        "almas": 46,
        "energia": 24,
        "sangue": 8,
        "cristais": 4,
        "ossos": 887,
        "po_osso": 8
      },
      "first_clear_multiplier": 1.7,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.25,
      "record_bonus": {
        "xp": 207,
        "almas": 6
      },
      "daily_bonus_key": "arena_daily_longer_clear",
      "weekly_cap_key": "arena_weekly_mastery",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "reward_s1_6d_d05",
      "display_name": "Season 1 6D D05 Clear",
      "description": "Perfil calibravel Season 1 para concluir arena PVE de 6 duelos na dificuldade rank 5.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "reward",
        "six_duels",
        "difficulty_5",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 480,
        "almas": 39,
        "energia": 20,
        "sangue": 6,
        "cristais": 1,
        "ossos": 442,
        "po_osso": 4
      },
      "first_clear_multiplier": 1.8,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.3,
      "record_bonus": {
        "xp": 86,
        "almas": 5
      },
      "daily_bonus_key": "arena_daily_longer_clear",
      "weekly_cap_key": "arena_weekly_mastery",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "reward_s1_6d_d06",
      "display_name": "Season 1 6D D06 Clear",
      "description": "Perfil calibravel Season 1 para concluir arena PVE de 6 duelos na dificuldade rank 6.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "reward",
        "six_duels",
        "difficulty_6",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 740,
        "almas": 44,
        "energia": 23,
        "sangue": 7,
        "cristais": 2,
        "ossos": 619,
        "po_osso": 6
      },
      "first_clear_multiplier": 1.8,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.25,
      "record_bonus": {
        "xp": 133,
        "almas": 6
      },
      "daily_bonus_key": "arena_daily_longer_clear",
      "weekly_cap_key": "arena_weekly_mastery",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "reward_s1_6d_d07",
      "display_name": "Season 1 6D D07 Clear",
      "description": "Perfil calibravel Season 1 para concluir arena PVE de 6 duelos na dificuldade rank 7.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "reward",
        "six_duels",
        "difficulty_7",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 1060,
        "almas": 50,
        "energia": 26,
        "sangue": 9,
        "cristais": 3,
        "ossos": 835,
        "po_osso": 8
      },
      "first_clear_multiplier": 1.8,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.25,
      "record_bonus": {
        "xp": 191,
        "almas": 7
      },
      "daily_bonus_key": "arena_daily_longer_clear",
      "weekly_cap_key": "arena_weekly_mastery",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "reward_s1_6d_d08",
      "display_name": "Season 1 6D D08 Clear",
      "description": "Perfil calibravel Season 1 para concluir arena PVE de 6 duelos na dificuldade rank 8.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "reward",
        "six_duels",
        "difficulty_8",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 1460,
        "almas": 55,
        "energia": 28,
        "sangue": 10,
        "cristais": 4,
        "ossos": 1103,
        "po_osso": 10
      },
      "first_clear_multiplier": 1.8,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.25,
      "record_bonus": {
        "xp": 263,
        "almas": 8
      },
      "daily_bonus_key": "arena_daily_longer_clear",
      "weekly_cap_key": "arena_weekly_mastery",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "reward_s1_6d_d09",
      "display_name": "Season 1 6D D09 Clear",
      "description": "Perfil calibravel Season 1 para concluir arena PVE de 6 duelos na dificuldade rank 9.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "season_001",
        "reward",
        "six_duels",
        "difficulty_9",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 1930,
        "almas": 61,
        "energia": 31,
        "sangue": 12,
        "cristais": 6,
        "ossos": 1417,
        "po_osso": 12
      },
      "first_clear_multiplier": 1.8,
      "completion_multiplier": 1,
      "repeat_multiplier": 0.25,
      "record_bonus": {
        "xp": 347,
        "almas": 9
      },
      "daily_bonus_key": "arena_daily_longer_clear",
      "weekly_cap_key": "arena_weekly_mastery",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    },
    {
      "id": "arena_repeat_progress",
      "display_name": "Repeat Progress Reward",
      "description": "Perfil de recompensa reduzida para repeticao ou progresso parcial sem primeira clear.",
      "version": 1,
      "enabled": true,
      "tags": [
        "PVE_ARENA_V1",
        "reward",
        "repeat",
        "partial",
        "CALIBRAVEL_ALPHA"
      ],
      "mode": "PVE_ARENA_V1",
      "resources": {
        "xp": 20,
        "almas": 1,
        "energia": 1,
        "ossos": 10
      },
      "first_clear_multiplier": 1,
      "completion_multiplier": 0.5,
      "repeat_multiplier": 0.25,
      "record_bonus": {},
      "daily_bonus_key": "arena_daily_repeat_soft_cap",
      "weekly_cap_key": "arena_weekly_participation",
      "season_cap_key": "season_001_arena_pve",
      "ledger_source": "arena_pve_v1"
    }
  ]
} as const;

export type PveArenaCatalog = typeof PVE_ARENA_CATALOG;
export type PveArenaDefinition = PveArenaCatalog["arenas"][number];
export type PveArenaDifficultyTier = PveArenaCatalog["difficulty_tiers"][number];
export type PveArenaEnemyDefinition = PveArenaCatalog["enemies"][number];
export type PveArenaRewardProfile = PveArenaCatalog["rewards"][number];
export type PveArenaBuffDefinition = PveArenaCatalog["buffs"][number];

export interface ArenaProgressSnapshot {
  tutorial_completed?: boolean;
  best_completed_difficulty?: number;
  best_completed_length?: number;
  metadata?: {
    completed_tiers?: Record<string, unknown>;
    completed_arenas?: Record<string, unknown>;
    [key: string]: unknown;
  };
  [key: string]: unknown;
}

export interface ArenaPlayerSnapshot {
  level?: number;
  power?: number;
  [key: string]: unknown;
}

export interface ArenaUnlockState {
  arena_id: string;
  difficulty_id: string;
  unlocked: boolean;
  reason: string;
}

export function arenaDefinitions(): PveArenaDefinition[] {
  return cloneArray(PVE_ARENA_CATALOG.arenas);
}

export function arenaDifficultyTiers(): PveArenaDifficultyTier[] {
  return cloneArray(PVE_ARENA_CATALOG.difficulty_tiers);
}

export function arenaTierById(
  arenaId: string,
  difficultyId: string,
): PveArenaDifficultyTier | null {
  const tier = PVE_ARENA_CATALOG.difficulty_tiers.find((item) =>
    item.arena_id === arenaId && item.difficulty_id === difficultyId
  );
  return tier === undefined ? null : clone(tier);
}

export function arenaRewardProfile(
  rewardProfileId: string,
): PveArenaRewardProfile | null {
  const reward = PVE_ARENA_CATALOG.rewards.find((item) => item.id === rewardProfileId);
  return reward === undefined ? null : clone(reward);
}

export function pveEnemyDefinition(enemyId: string): PveArenaEnemyDefinition | null {
  const enemy = PVE_ARENA_CATALOG.enemies.find((item) => item.id === enemyId);
  return enemy === undefined ? null : clone(enemy);
}

export function arenaBuffDefinitions(): PveArenaBuffDefinition[] {
  return cloneArray(PVE_ARENA_CATALOG.buffs);
}

export function arenaTierUnlockState(
  progress: ArenaProgressSnapshot | null | undefined,
  player: ArenaPlayerSnapshot | null | undefined,
  arenaId?: string,
  difficultyId?: string,
): ArenaUnlockState[] {
  const tiers = PVE_ARENA_CATALOG.difficulty_tiers.filter((tier) =>
    (arenaId === undefined || tier.arena_id === arenaId) &&
    (difficultyId === undefined || tier.difficulty_id === difficultyId)
  );
  return tiers.map((tier) => unlockStateForTier(tier, progress ?? {}, player ?? {}));
}

function unlockStateForTier(
  tier: PveArenaDifficultyTier,
  progress: ArenaProgressSnapshot,
  player: ArenaPlayerSnapshot,
): ArenaUnlockState {
  const arena = PVE_ARENA_CATALOG.arenas.find((item) => item.id === tier.arena_id);
  if (arena === undefined) {
    return {
      arena_id: tier.arena_id,
      difficulty_id: tier.difficulty_id,
      unlocked: false,
      reason: "Arena desconhecida",
    };
  }

  const arenaGate = arenaUnlockReason(arena, progress);
  if (arenaGate !== "") {
    return {
      arena_id: tier.arena_id,
      difficulty_id: tier.difficulty_id,
      unlocked: false,
      reason: arenaGate,
    };
  }

  const playerLevel = safeNumber(player.level, 1);
  if (playerLevel + 1 < tier.recommended_level_min) {
    return {
      arena_id: tier.arena_id,
      difficulty_id: tier.difficulty_id,
      unlocked: false,
      reason: `Recomendada para level ${tier.recommended_level_min}`,
    };
  }

  const bestRank = safeNumber(progress.best_completed_difficulty, -1);
  if (tier.difficulty_rank > bestRank + 1) {
    return {
      arena_id: tier.arena_id,
      difficulty_id: tier.difficulty_id,
      unlocked: false,
      reason: "Conclua a dificuldade anterior",
    };
  }

  return {
    arena_id: tier.arena_id,
    difficulty_id: tier.difficulty_id,
    unlocked: true,
    reason: "Disponivel",
  };
}

function arenaUnlockReason(
  arena: PveArenaDefinition,
  progress: ArenaProgressSnapshot,
): string {
  const unlock = arena.unlock as { type?: string; arena_id?: string };
  if (unlock.type === "always") {
    return "";
  }
  if (unlock.type !== "arena_first_clear" || unlock.arena_id === undefined) {
    return "Bloqueio de arena desconhecido";
  }
  if (hasCompletedArena(progress, unlock.arena_id)) {
    return "";
  }
  const requiredArena = PVE_ARENA_CATALOG.arenas.find((item) => item.id === unlock.arena_id);
  return requiredArena === undefined
    ? "Conclua a arena anterior"
    : `Conclua ${requiredArena.display_name}`;
}

function hasCompletedArena(progress: ArenaProgressSnapshot, arenaId: string): boolean {
  if (arenaId === "arena_tutorial_cinzas" && progress.tutorial_completed === true) {
    return true;
  }
  const completedArenas = progress.metadata?.completed_arenas;
  if (completedArenas !== undefined && completedArenas[arenaId] === true) {
    return true;
  }
  const completedTiers = progress.metadata?.completed_tiers;
  if (completedTiers !== undefined) {
    for (const key of Object.keys(completedTiers)) {
      if (key.startsWith(`${arenaId}:`) && completedTiers[key] === true) {
        return true;
      }
    }
  }
  const arena = PVE_ARENA_CATALOG.arenas.find((item) => item.id === arenaId);
  return arena !== undefined && safeNumber(progress.best_completed_length, 0) >= arena.duel_count;
}

function safeNumber(value: unknown, fallback: number): number {
  return typeof value === "number" && Number.isFinite(value) ? value : fallback;
}

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

function cloneArray<T>(value: readonly T[]): T[] {
  return value.map((item) => clone(item));
}
